# ==============================================================================
# SHINY DASHBOARD: NIH Retraction Cost 
# ==============================================================================
# Reads three pre-processed CSVs that the Python pipeline produces and renders
# a multi-tab dashboard. CPI data is loaded from a cached CSV (annual_cpi.csv)
# regenerated by the quarterly pipeline; this avoids a network call to FRED on
# every cold start of the app on shinyapps.io.
# ==============================================================================

# 1. LIBRARIES & GLOBAL SETUP
# ------------------------------------------------------------------------------
library(shiny)
library(tidyverse)
library(scales)
library(lubridate)
library(DT)
library(plotly)
library(shinycssloaders)

# --- INPUT FILES ---
papers_file  <- "data/processed/FINAL_Retractions_Costs_and_Pubs.csv"
authors_file <- "data/processed/Author_Funding_Matches.csv"
cpi_file     <- "data/processed/annual_cpi.csv"

# --- ANNUAL CPI ---
# Primary source: cached CSV produced by src/cpi_fetcher.py (quarterly cron).
# Fallback (only if the CSV is missing): live FRED pull via quantmod, kept as a
# safety net so the app still works in a fresh local clone.
load_annual_cpi <- function(path = cpi_file) {
  
  if (file.exists(path)) {
    df <- readr::read_csv(path, show_col_types = FALSE)
    if (!"Inflation_Multiplier" %in% colnames(df)) {
      current_cpi <- max(df$CPI, na.rm = TRUE)
      df$Inflation_Multiplier <- current_cpi / df$CPI
    }
    return(df[, c("Fiscal_Year", "CPI", "Inflation_Multiplier")])
  }
  
  warning(
    "annual_cpi.csv not found; falling back to live FRED download. ",
    "Run `python -m src.cpi_fetcher` to generate the cache."
  )
  
  if (!requireNamespace("quantmod", quietly = TRUE)) {
    install.packages("quantmod", repos = "https://cloud.r-project.org")
  }
  
  cpi_xts <- quantmod::getSymbols("CPIAUCSL", src = "FRED", auto.assign = FALSE)
  monthly <- data.frame(Date = zoo::index(cpi_xts), CPI = as.numeric(cpi_xts))
  annual <- monthly %>%
    mutate(Fiscal_Year = lubridate::year(Date)) %>%
    group_by(Fiscal_Year) %>%
    summarise(CPI = mean(CPI, na.rm = TRUE), .groups = "drop")
  
  current_cpi <- max(annual$CPI, na.rm = TRUE)
  annual %>% mutate(Inflation_Multiplier = current_cpi / CPI)
}

annual_cpi <- load_annual_cpi()

# --- LOAD PAPERS ---
df_papers <- read_csv(papers_file, show_col_types = FALSE) %>%
  mutate(
    Publication_Year = as.numeric(str_extract(OriginalPaperDate, "(?<=/)\\d{4}")),
    Retraction_Year  = as.numeric(str_extract(RetractionDate,    "(?<=/)\\d{4}")),
    retraction_lag   = Retraction_Year - Publication_Year,
    attributed_cost_raw = ifelse(
      !is.na(Total_Grant_Pubs) & Total_Grant_Pubs > 0,
      Total_NIH_Funding_Cost / Total_Grant_Pubs,
      NA
    )
  ) %>%
  left_join(annual_cpi, by = c("Publication_Year" = "Fiscal_Year")) %>%
  mutate(attributed_cost_adjusted = attributed_cost_raw * Inflation_Multiplier)

# --- LOAD AUTHORS ---
df_authors_raw <- read_csv(authors_file, show_col_types = FALSE)

author_retractions <- df_authors_raw %>%
  group_by(Original_Author_Name) %>%
  summarise(Num_Retractions = n_distinct(Record_ID), .groups = "drop")

df_authors <- df_authors_raw %>%
  group_by(Original_Author_Name) %>%
  mutate(First_Retraction_Year = min(Retraction_Year, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(diff_retracted = Fiscal_Year - First_Retraction_Year) %>%
  distinct(Original_Author_Name, Grant_ID, Fiscal_Year, Funding_Amount, diff_retracted) %>%
  left_join(annual_cpi, by = "Fiscal_Year") %>%
  mutate(Funding_Adjusted = Funding_Amount * Inflation_Multiplier) %>%
  left_join(author_retractions, by = "Original_Author_Name")

# --- GLOBAL PLOT THEME ---
# Transparent backgrounds so plots blend with the dashboard cards.
dashboard_theme <- theme_classic(base_size = 12) +
  theme(
    legend.position  = "top",
    legend.title     = element_blank(),
    plot.background  = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA),
    panel.grid.major.y = element_line(color = "gray90", linewidth = 0.5)
  )

corporate_colors <- c("NIH Funded" = "#005b96",
                      "Not NIH Funded / Other" = "gray70")


# 2. CUSTOM CSS (NIH RePORTER look-alike)
# ------------------------------------------------------------------------------
nih_css <- "
  /* Light gray page background */
  body { background-color: #f4f6f9; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; }

  /* Dark top navbar */
  .navbar-inverse { background-color: #2b2b2b; border-color: #1a1a1a; }
  .navbar-inverse .navbar-brand { color: #ffffff; font-weight: bold; font-size: 22px; }
  .navbar-inverse .navbar-nav>li>a { color: #dddddd; font-weight: bold; }
  .navbar-inverse .navbar-nav>li>a:hover { color: #ffffff; }

  /* NIH-style hero banner with blue/teal gradient */
  .hero-banner {
    background: linear-gradient(135deg, #09375e 0%, #13778a 100%);
    color: white;
    padding: 40px 30px;
    margin-top: -20px; /* pull flush against the navbar */
    margin-bottom: 30px;
    margin-left: -15px;
    margin-right: -15px;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
  }
  .hero-banner h2 { margin-top: 0; font-weight: bold; }
  .kpi-box {
    background: rgba(255, 255, 255, 0.15);
    border: 1px solid rgba(255, 255, 255, 0.3);
    border-radius: 5px;
    padding: 15px;
    text-align: center;
    word-wrap: break-word;
    overflow-wrap: break-word;
  }
  .kpi-box h3 { margin: 0; font-size: clamp(16px, 2.5vw, 28px); font-weight: bold; }
  .kpi-box p { margin: 0; font-size: 14px; text-transform: uppercase; }

  /* White cards with a teal top border */
  .nih-card {
    background: white;
    border-radius: 4px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    border-top: 4px solid #17a2b8;
    padding: 20px;
    margin-bottom: 25px;
  }
  .nih-card h4 {
    color: #333;
    font-weight: bold;
    margin-top: 0;
    margin-bottom: 20px;
    font-size: 18px;
  }
"

# 3. USER INTERFACE (UI)
# ------------------------------------------------------------------------------
mtime_val <- file.info(papers_file)$mtime
months_eng <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
last_updated_str <- paste0(months_eng[as.integer(format(mtime_val, "%m"))], " ", format(mtime_val, "%d, %Y"))

ui <- navbarPage(
  title = "NIH Retraction Cost Dashboard",
  inverse = TRUE,
  header = tags$head(
    tags$style(HTML(nih_css)),
    tags$script(HTML(sprintf("
      $(document).ready(function() {
        $('<p class=\"navbar-text navbar-right\" style=\"margin-right: 15px; color: #dddddd;\">Last updated: %s</p>').appendTo('.navbar > .container-fluid');
      });
    ", last_updated_str)))
  ),
  
  # --- TAB 1: Summary ---
  tabPanel("Summary Stats",
           fluidRow(
             column(12,
                    div(class = "hero-banner",
                        fluidRow(
                          column(4,
                                 h2("Welcome to the NIH Retraction Cost Dashboard"),
                                 p("Analyzing the financial footprint of U.S. retracted research funded by the NIH.")
                          ),
                          column(8,
                                 fluidRow(
                                   column(4, div(class = "kpi-box", p("U.S. Retracted Papers"), h3(textOutput("kpi_papers")))),
                                   column(4, div(class = "kpi-box", p("NIH Funded"), h3(textOutput("kpi_nih_papers")))),
                                   column(4, div(class = "kpi-box", p("Adj. Funding Lost"), h3(textOutput("kpi_funding"))))
                                 )
                          )
                        )
                    )
             )
           ),
           fluidPage(
             fluidRow(
               column(12,
                      div(class = "nih-card",
                          h4("Retraction Costs Summary (Raw and FRED CPI Adjusted)"),
                          withSpinner(DTOutput("cost_summary_table"), type = 4, color = "#17a2b8"),
                          p(em("Note: Adjusted Attributed Cost reflects values adjusted for inflation to current dollars using the Consumer Price Index for All Urban Consumers (CPI-AUCSL) provided by the Federal Reserve Economic Data (FRED)."),
                            style = "color: gray; font-size: 12px; margin-top: 10px;")
                      )
               )
             )
           )
  ),
  
  # --- TAB 2: Article Characteristics ---
  tabPanel("Article Characteristics",
           fluidPage(
             br(),
             fluidRow(
               column(6, div(class = "nih-card", h4("Publication Year"), withSpinner(plotlyOutput("plot_pub_year"), type = 4, color = "#17a2b8"))),
               column(6, div(class = "nih-card", h4("Retraction Year"), withSpinner(plotlyOutput("plot_ret_year"), type = 4, color = "#17a2b8")))
             ),
             fluidRow(
               column(6, div(class = "nih-card",
                             h4("Lag Between Publication and Retraction"),
                             withSpinner(plotlyOutput("plot_retraction_lag"), type = 4, color = "#17a2b8"),
                             uiOutput("lag_note"))),
               column(6, div(class = "nih-card",
                             h4("Lag Summary Statistics (years)"),
                             withSpinner(tableOutput("lag_stats_table"), type = 4, color = "#17a2b8")))
             ),
             fluidRow(
               column(6, div(class = "nih-card", h4("Top Reasons for Retraction"), withSpinner(plotlyOutput("plot_reasons"), type = 4, color = "#17a2b8"))),
               column(6, div(class = "nih-card",
                             h4("Scientific Domains"),
                             withSpinner(plotlyOutput("plot_domains"), type = 4, color = "#17a2b8"),
                             p(em("Note: A single paper can have multiple subjects, but each broad category is counted at most once per paper."),
                               style = "color: gray; font-size: 12px; margin-top: 10px;")))
             ),
             fluidRow(
               column(12, div(class = "nih-card",
                              h4("Top Retracted Publishers"),
                              withSpinner(plotlyOutput("plot_publishers"), type = 4, color = "#17a2b8"),
                              p(em("Note: Publishers were grouped by parent companies where possible. 'Springer Nature' includes Springer, Nature, BMC, Palgrave. 'Elsevier' includes Cell Press, Lancet. 'Hindawi' has been separated from 'Wiley' to show its specific impact. 'Taylor & Francis' includes Routledge, Dove Medical Press."),
                                style = "color: gray; font-size: 12px; margin-top: 10px;")))
             )
           )
  ),
  
  # --- TAB 3: Author consequences ---
  tabPanel("Author consequences",
           fluidPage(
             br(),
             fluidRow(
               column(8, p(strong("Note:"), " The charts below show CPI-adjusted NIH funding and activity for authors who had a paper retracted. Data is grouped by year offset relative to each author's first retraction (year 0). ",
                            style = "color: gray; font-style: italic; margin-bottom: 20px;")),
               column(4, selectInput("author_cohort_filter", HTML("<span style='white-space: nowrap;'>Sensitivity Analysis (Retracted Papers per Author):</span>"), 
                                     choices = c("All Authors" = "all", "1 Paper Retracted" = "one", ">1 Papers Retracted" = "more"),
                                     selected = "all", width = "100%"))
             ),
             fluidRow(
               column(6, div(class = "nih-card",
                             h4("Average Funding Granted to Retracted Authors"), # TITULO MODIFICADO
                             withSpinner(plotlyOutput("plot_avg_funding"), type = 4, color = "#17a2b8"),
                             uiOutput("plot_avg_funding_note"))),
               column(6, div(class = "nih-card",
                             h4("Average Funding Statistics"), # TITULO MODIFICADO
                             withSpinner(uiOutput("stats_avg_funding"), type = 4, color = "#17a2b8")))
             ),
             fluidRow(
               column(6, div(class = "nih-card",
                             h4("Total Active Grants"),
                             withSpinner(plotlyOutput("plot_active_grants"), type = 4, color = "#17a2b8"),
                             p(em("Note: Because multiple retracted authors can be funded by the exact same NIH grant (e.g., as co-investigators), the total distinct grants across subgroups will not sum perfectly to the overall 'All Authors' total due to these shared grants being counted in both groups."), style = "color: gray; font-size: 12px; margin-top: 10px;"))),
               column(6, div(class = "nih-card",
                             h4("Active Grants Statistics"),
                             withSpinner(uiOutput("stats_active_grants"), type = 4, color = "#17a2b8")))
             ),
             fluidRow(
               column(6, div(class = "nih-card",
                             h4("Percent Change in Average Funding (Pre vs. Post Retraction)"),
                             withSpinner(plotlyOutput("plot_dumbbell_funding", height = "400px"), type = 4, color = "#17a2b8"))),
               column(6, div(class = "nih-card",
                             h4("Distribution of Individual % Change"),
                             withSpinner(plotlyOutput("plot_pct_change_dist", height = "400px"), type = 4, color = "#17a2b8")))
             )
           )
  )
)

# 4. SERVER LOGIC
# ------------------------------------------------------------------------------
server <- function(input, output, session) {
  
  # --- KPI tiles ---
  output$kpi_papers <- renderText({ comma(nrow(df_papers)) })
  output$kpi_funding <- renderText({ dollar(sum(df_papers$attributed_cost_adjusted, na.rm = TRUE), accuracy = 1) })
  output$kpi_nih_papers <- renderText({ comma(sum(!is.na(df_papers$attributed_cost_raw))) })
  
  # --- Summary table ---
  output$cost_summary_table <- renderDT({
    cost_summary_df <- data.frame(
      Metric = c("Mean", "Median", "Q1", "Q3", "Total Funding Lost"),
      Raw_Attributed_Cost = c(
        mean(df_papers$attributed_cost_raw, na.rm = TRUE), median(df_papers$attributed_cost_raw, na.rm = TRUE),
        quantile(df_papers$attributed_cost_raw, 0.25, na.rm = TRUE), quantile(df_papers$attributed_cost_raw, 0.75, na.rm = TRUE),
        sum(df_papers$attributed_cost_raw, na.rm = TRUE)
      ),
      Adjusted_Cost_Current = c(
        mean(df_papers$attributed_cost_adjusted, na.rm = TRUE), median(df_papers$attributed_cost_adjusted, na.rm = TRUE),
        quantile(df_papers$attributed_cost_adjusted, 0.25, na.rm = TRUE), quantile(df_papers$attributed_cost_adjusted, 0.75, na.rm = TRUE),
        sum(df_papers$attributed_cost_adjusted, na.rm = TRUE)
      )
    ) %>%
      mutate(
        Raw_Attributed_Cost   = dollar(Raw_Attributed_Cost,   accuracy = 1),
        Adjusted_Cost_Current = dollar(Adjusted_Cost_Current, accuracy = 1)
      ) %>%
      rename(
        `Raw Attributed Cost` = Raw_Attributed_Cost,
        `Adjusted Attributed Cost` = Adjusted_Cost_Current
      )
    
    datatable(cost_summary_df,
              class = 'row-border',
              selection = 'none',
              options = list(dom = 't', ordering = FALSE, paging = FALSE),
              rownames = FALSE)
  })
  
  # --- Paper-level plots (Plotly) ---
  output$plot_pub_year <- renderPlotly({
    p <- df_papers %>% drop_na(Publication_Year) %>% filter(Publication_Year >= 1970) %>%
      mutate(Funding_Status = ifelse(!is.na(Total_NIH_Funding_Cost) & Total_NIH_Funding_Cost > 0, "NIH Funded", "Not NIH Funded / Other")) %>%
      rename(`Publication Year` = Publication_Year, `Funding Status` = Funding_Status) %>%
      count(`Publication Year`, `Funding Status`, name = "No. of articles") %>%
      ggplot(aes(x = `Publication Year`, y = `No. of articles`, fill = `Funding Status`)) +
      geom_col(width = 1, color = "white", position = "stack") +
      scale_fill_manual(values = corporate_colors) +
      scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
      labs(x = "Publication Year", y = "No. of articles") + dashboard_theme
    ggplotly(p, tooltip = c("x", "y", "fill")) %>% layout(legend = list(orientation = "h", x = 0, y = 1.15, title = list(text = "")), margin = list(t = 50))
  })
  
  output$plot_ret_year <- renderPlotly({
    p <- df_papers %>% drop_na(Retraction_Year) %>% filter(Retraction_Year >= 1970) %>%
      mutate(Funding_Status = ifelse(!is.na(Total_NIH_Funding_Cost) & Total_NIH_Funding_Cost > 0, "NIH Funded", "Not NIH Funded / Other")) %>%
      rename(`Retraction Year` = Retraction_Year, `Funding Status` = Funding_Status) %>%
      count(`Retraction Year`, `Funding Status`, name = "No. of articles") %>%
      ggplot(aes(x = `Retraction Year`, y = `No. of articles`, fill = `Funding Status`)) +
      geom_col(width = 1, color = "white", position = "stack") +
      scale_fill_manual(values = corporate_colors) +
      scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
      labs(x = "Retraction Year", y = "No. of articles") + dashboard_theme
    ggplotly(p, tooltip = c("x", "y", "fill")) %>% layout(legend = list(orientation = "h", x = 0, y = 1.15, title = list(text = "")), margin = list(t = 50))
  })
  
  # --- Retraction-lag histogram + summary ---
  LAG_AXIS_MAX <- 25
  
  lag_diagnostics <- reactive({
    full <- df_papers %>%
      mutate(Funding_Status = ifelse(
        !is.na(Total_NIH_Funding_Cost) & Total_NIH_Funding_Cost > 0,
        "NIH Funded", "Not NIH Funded / Other"
      ))
    n_total    <- nrow(full)
    n_missing  <- sum(is.na(full$retraction_lag))
    n_negative <- sum(full$retraction_lag < 0, na.rm = TRUE)
    valid      <- full %>% filter(!is.na(retraction_lag) & retraction_lag >= 0)
    n_outliers <- sum(valid$retraction_lag > LAG_AXIS_MAX, na.rm = TRUE)
    list(total = n_total, missing = n_missing, negative = n_negative, outliers = n_outliers, valid = valid)
  })
  
  output$plot_retraction_lag <- renderPlotly({
    d <- lag_diagnostics()$valid
    p <- d %>%
      rename(`Retraction Lag` = retraction_lag, `Funding Status` = Funding_Status) %>%
      count(`Retraction Lag`, `Funding Status`, name = "No. of articles") %>%
      ggplot(aes(x = `Retraction Lag`, y = `No. of articles`, fill = `Funding Status`)) +
      geom_col(width = 1, color = "white", position = "stack") +
      scale_fill_manual(values = corporate_colors) +
      coord_cartesian(xlim = c(0, LAG_AXIS_MAX)) +
      scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
      labs(x = "Years between Publication and Retraction", y = "No. of articles") +
      dashboard_theme
    ggplotly(p, tooltip = c("x", "y", "fill")) %>%
      layout(legend = list(orientation = "h", x = 0, y = 1.15, title = list(text = "")), margin = list(t = 50))
  })
  
  output$lag_note <- renderUI({
    diag <- lag_diagnostics()
    HTML(sprintf(
      paste0(
        "<p style='color: gray; font-size: 12px; margin-top: 10px;'>",
        "<em>Note: Distribution of the number of years elapsed between a paper's ",
        "publication date and its retraction date. ",
        "The X axis is capped at %d years for readability; ",
        "<b>%s</b> paper(s) with a lag &gt; %d year(s) are excluded from the plot ",
        "but included in the summary statistics.</em></p>"
      ),
      LAG_AXIS_MAX, format(diag$outliers, big.mark = ","), LAG_AXIS_MAX
    ))
  })
  
  output$lag_stats_table <- renderTable({
    valid <- lag_diagnostics()$valid
    
    summarise_lag <- function(v) {
      if (length(v) == 0) return(c("-", "-", "-", "-", "0"))
      qs <- quantile(v, probs = c(0.25, 0.5, 0.75), na.rm = TRUE)
      c(sprintf("%.2f", mean(v, na.rm = TRUE)), sprintf("%.2f", qs[2]),
        sprintf("%.2f", qs[1]), sprintf("%.2f", qs[3]), format(length(v), big.mark = ","))
    }
    
    nih_v <- valid %>% filter(Funding_Status == "NIH Funded") %>% pull(retraction_lag)
    oth_v <- valid %>% filter(Funding_Status == "Not NIH Funded / Other") %>% pull(retraction_lag)
    
    data.frame(
      Statistic = c("Mean (years)", "Median (years)", "Q1 (years)", "Q3 (years)", "N papers"),
      `NIH Funded` = summarise_lag(nih_v),
      `Not NIH Funded / Other` = summarise_lag(oth_v),
      check.names = FALSE
    )
  }, striped = TRUE, hover = TRUE, spacing = "s", width = "100%")
  
  output$plot_publishers <- renderPlotly({
    publishers_data <- df_papers %>%
      drop_na(Publisher) %>%
      mutate(Publisher = str_trim(Publisher)) %>%
      filter(Publisher != "") %>%
      mutate(
        Funding_Status = ifelse(
          !is.na(Total_NIH_Funding_Cost) & Total_NIH_Funding_Cost > 0,
          "NIH Funded", "Not NIH Funded / Other"
        ),
        Publisher_Group = case_when(
          str_detect(Publisher, "(?i)Hindawi")                                         ~ "Hindawi (Wiley)",
          str_detect(Publisher, "(?i)Springer|Nature|BioMed Central|BMC|Palgrave")     ~ "Springer Nature",
          str_detect(Publisher, "(?i)Elsevier|Cell Press|Lancet|Pergamon")             ~ "Elsevier",
          str_detect(Publisher, "(?i)Wiley")                                           ~ "Wiley (excl. Hindawi)",
          str_detect(Publisher, "(?i)Taylor & Francis|Taylor and Francis|Routledge|Dove Medical") ~ "Taylor & Francis",
          str_detect(Publisher, "(?i)SAGE")                                            ~ "SAGE Publications",
          str_detect(Publisher, "(?i)IEEE")                                            ~ "IEEE",
          str_detect(Publisher, "(?i)MDPI")                                            ~ "MDPI",
          str_detect(Publisher, "(?i)Frontiers")                                       ~ "Frontiers",
          str_detect(Publisher, "(?i)Public Library of Science|PLOS|PLoS")             ~ "PLOS",
          str_detect(Publisher, "(?i)Oxford University Press|OUP")                     ~ "Oxford University Press",
          str_detect(Publisher, "(?i)Cambridge University Press|CUP")                  ~ "Cambridge University Press",
          TRUE                                                                         ~ Publisher
        )
      )
    
    top_20 <- publishers_data %>%
      count(Publisher_Group, sort = TRUE) %>%
      slice_head(n = 20) %>%
      pull(Publisher_Group)
    
    p <- publishers_data %>%
      filter(Publisher_Group %in% top_20) %>%
      mutate(Publisher_Group = factor(Publisher_Group, levels = rev(top_20))) %>%
      rename(`Publisher Group` = Publisher_Group, `Funding Status` = Funding_Status) %>%
      count(`Publisher Group`, `Funding Status`, name = "No. of articles") %>%
      ggplot(aes(y = `Publisher Group`, x = `No. of articles`, fill = `Funding Status`)) +
      geom_col(color = "white", position = "stack", width = 0.8) +
      scale_x_continuous(expand = expansion(mult = c(0, 0.05))) +
      scale_fill_manual(values = corporate_colors) +
      labs(y = "", x = "No. of articles") +
      dashboard_theme +
      theme(panel.grid.major.y = element_blank(), panel.grid.major.x = element_line(color = "gray90", linewidth = 0.5))
    
    n_categories <- length(top_20)
    
    ggplotly(p, tooltip = c("x", "y", "fill")) %>%
      layout(yaxis = list(range = c(0.5, n_categories + 0.5)),
             legend = list(orientation = "h", x = -0.5, y = 1.15, title = list(text = "")), 
             margin = list(t = 80, r = 20))
  })
  
  output$plot_domains <- renderPlotly({
    domains_data <- df_papers %>%
      drop_na(Subject) %>%
      mutate(Paper_ID = row_number()) %>%
      separate_rows(Subject, sep = ";") %>%
      mutate(Subject = str_trim(Subject)) %>%
      filter(Subject != "") %>%
      mutate(
        Funding_Status = ifelse(
          !is.na(Total_NIH_Funding_Cost) & Total_NIH_Funding_Cost > 0,
          "NIH Funded", "Not NIH Funded / Other"
        ),
        Acronym = str_extract(Subject, "^\\([^)]+\\)")
      ) %>%
      mutate(
        Domain_Full = case_when(
          Acronym == "(B/T)" ~ "Business & Technology",
          Acronym == "(BLS)" ~ "Biological Sciences",
          Acronym == "(ENV)" ~ "Environmental Sciences",
          Acronym == "(HSC)" ~ "Health Sciences",
          Acronym == "(HUM)" ~ "Humanities",
          Acronym == "(PHY)" ~ "Physical Sciences",
          Acronym == "(SOC)" ~ "Social Sciences",
          TRUE               ~ NA_character_
        )
      ) %>%
      filter(!is.na(Domain_Full)) %>%
      distinct(Paper_ID, Domain_Full, Funding_Status)
    
    domain_order <- domains_data %>% count(Domain_Full, sort = TRUE) %>% pull(Domain_Full)
    
    p <- domains_data %>%
      mutate(Domain_Full = factor(Domain_Full, levels = rev(domain_order))) %>%
      rename(`Domain Full` = Domain_Full, `Funding Status` = Funding_Status) %>%
      count(`Domain Full`, `Funding Status`, name = "No. of articles") %>%
      ggplot(aes(x = `Domain Full`, y = `No. of articles`, fill = `Funding Status`)) + geom_col(color = "white", position = "stack") + coord_flip() +
      scale_fill_manual(values = corporate_colors) + scale_y_continuous(expand = expansion(mult = c(0, 0.05))) + labs(x = "", y = "No. of articles") + dashboard_theme +
      theme(panel.grid.major.y = element_blank(), panel.grid.major.x = element_line(color = "gray90", linewidth = 0.5))
    
    ggplotly(p, tooltip = c("x", "y", "fill")) %>% layout(legend = list(orientation = "h", x = -0.5, y = 1.15, title = list(text = "")), margin = list(t = 50))
  })
  
  output$plot_reasons <- renderPlotly({
    reasons_data <- df_papers %>% drop_na(Reason) %>% mutate(Paper_ID = row_number()) %>% separate_rows(Reason, sep = ";") %>%
      mutate(Reason = str_trim(Reason)) %>% filter(Reason != "", !str_detect(Reason, "^Investigation")) %>%
      mutate(Funding_Status = ifelse(!is.na(Total_NIH_Funding_Cost) & Total_NIH_Funding_Cost > 0, "NIH Funded", "Not NIH Funded / Other")) %>%
      distinct(Paper_ID, Reason, Funding_Status)
    
    top_10 <- reasons_data %>% count(Reason, sort = TRUE) %>% slice_head(n = 10) %>% pull(Reason)
    
    p <- reasons_data %>% filter(Reason %in% top_10) %>% mutate(Reason = factor(Reason, levels = rev(top_10))) %>%
      rename(`Funding Status` = Funding_Status) %>%
      count(Reason, `Funding Status`, name = "No. of articles") %>%
      ggplot(aes(x = Reason, y = `No. of articles`, fill = `Funding Status`)) + geom_col(color = "white", position = "stack") + coord_flip() +
      scale_fill_manual(values = corporate_colors) + scale_y_continuous(expand = expansion(mult = c(0, 0.05))) + labs(x = "", y = "No. of articles") + dashboard_theme +
      theme(panel.grid.major.y = element_blank(), panel.grid.major.x = element_line(color = "gray90", linewidth = 0.5))
    
    ggplotly(p, tooltip = c("x", "y", "fill")) %>% layout(legend = list(orientation = "h", x = -0.5, y = 1.15, title = list(text = "")), margin = list(t = 50))
  })
  
  # --- Filtered Authors Reactive ---
  filtered_authors <- reactive({
    req(input$author_cohort_filter)
    if (input$author_cohort_filter == "one") {
      df_authors %>% filter(Num_Retractions == 1)
    } else if (input$author_cohort_filter == "more") {
      df_authors %>% filter(Num_Retractions > 1)
    } else {
      df_authors
    }
  })

  # --- Longitudinal impact ---
  df_timeline <- reactive({
    fa <- filtered_authors()
    total_cohort_authors <- n_distinct(fa$Original_Author_Name)
    
    fa %>% filter(diff_retracted >= -3 & diff_retracted <= 3) %>%
      group_by(diff_retracted) %>%
      summarise(Total_Adjusted_Funding = sum(Funding_Adjusted, na.rm = TRUE),
                Active_Grants = n_distinct(Grant_ID[!is.na(Grant_ID)])) %>%
      mutate(Cohort_Authors = total_cohort_authors,
             Average_Funding_Per_Author = Total_Adjusted_Funding / total_cohort_authors,
             Period_Label = ifelse(diff_retracted == 0, "Retraction Year (0)", "Normal Years"))
  })
  
  timeline_colors <- c("Retraction Year (0)" = "#cccccc", "Normal Years" = "#005b96")
  
  output$plot_active_grants <- renderPlotly({
    tl <- df_timeline()
    p <- ggplot(tl, aes(x = diff_retracted, y = Active_Grants, text = paste("Year offset:", diff_retracted, "<br>Active Grants:", comma(Active_Grants)))) +
      geom_vline(xintercept = 0, color = "#d9534f", linetype = "dashed", linewidth = 0.8) +
      geom_line(color = "#005b96", linewidth = 0.5, group = 1) +
      geom_point(aes(color = Period_Label), size = 2) +
      scale_color_manual(values = timeline_colors) +
      scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
      scale_y_continuous(labels = comma, limits = c(0, NA)) +
      labs(x = "Years from First Retraction", y = "Total Active Grants") +
      dashboard_theme + theme(legend.position = "none")
    ggplotly(p, tooltip = "text") %>% layout(showlegend = FALSE)
  })
  
  output$plot_total_funding <- renderPlotly({
    tl <- df_timeline()
    p <- ggplot(tl, aes(x = diff_retracted, y = Total_Adjusted_Funding, text = paste("Year offset:", diff_retracted, "<br>Total Funding:", dollar(Total_Adjusted_Funding)))) +
      geom_vline(xintercept = 0, color = "#d9534f", linetype = "dashed", linewidth = 0.8) +
      geom_line(color = "#005b96", linewidth = 0.5, group = 1) +
      geom_point(aes(color = Period_Label), size = 2) +
      scale_color_manual(values = timeline_colors) +
      scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
      scale_y_continuous(labels = label_dollar()) +
      labs(x = "Years from First Retraction", y = "Total CPI-adjusted Funding ($)") +
      dashboard_theme + theme(legend.position = "none")
    ggplotly(p, tooltip = "text") %>% layout(showlegend = FALSE)
  })
  
  output$plot_avg_funding <- renderPlotly({
    tl <- df_timeline()
    p <- ggplot(tl, aes(x = diff_retracted, y = Average_Funding_Per_Author, 
                        text = paste("Year offset:", diff_retracted, "<br>Average Funding:", dollar(Average_Funding_Per_Author)))) +
      geom_vline(xintercept = 0, color = "#d9534f", linetype = "dashed", linewidth = 0.8) +
      geom_line(color = "#005b96", linewidth = 0.5, group = 1) +
      geom_point(aes(color = Period_Label), size = 2) +
      scale_color_manual(values = timeline_colors) + 
      scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
      scale_y_continuous(labels = label_dollar(), limits = c(0, NA)) +
      labs(x = "Years from First Retraction", y = "Average Funding ($)") +
      dashboard_theme + theme(legend.position = "none")
    ggplotly(p, tooltip = "text") %>% layout(showlegend = FALSE)
  })
  
  output$plot_dumbbell_funding <- renderPlotly({
    pd <- paired_data()
    tl <- df_timeline()
    
    # Calculate means exactly as in stats_avg_funding to match the global statistics
    mean_pre <- mean(tl$Average_Funding_Per_Author[tl$diff_retracted %in% c(-3, -2, -1)], na.rm = TRUE)
    mean_post <- mean(tl$Average_Funding_Per_Author[tl$diff_retracted %in% c(1, 2, 3)], na.rm = TRUE)
    pct_change <- (mean_post - mean_pre) / mean_pre
    if (is.nan(pct_change) | is.infinite(pct_change)) pct_change <- 0
    
    # Random sample for interactive Plotly to prevent browser crash
    set.seed(42)
    pd_sample <- pd %>% 
      sample_n(min(300, n())) %>%
      mutate(Indiv_Pct_Change = ifelse(Annual_Funding_Pre > 0, 
                                       (Annual_Funding_Post - Annual_Funding_Pre) / Annual_Funding_Pre, 
                                       ifelse(Annual_Funding_Post > 0, 1, 0))) %>%
      mutate(Indiv_Pct_Change_Capped = pmax(pmin(Indiv_Pct_Change, 3), -1))
    
    # Long format for spaghetti
    df_long <- pd_sample %>%
      select(Original_Author_Name, `Pre-Retraction` = Annual_Funding_Pre, `Post-Retraction` = Annual_Funding_Post, Indiv_Pct_Change_Capped, Indiv_Pct_Change) %>%
      pivot_longer(cols = c(`Pre-Retraction`, `Post-Retraction`), names_to = "Period", values_to = "Funding") %>%
      mutate(Period = factor(Period, levels = c("Pre-Retraction", "Post-Retraction")))
      
    # Mean format
    df_mean <- data.frame(
      Period = factor(c("Pre-Retraction", "Post-Retraction"), levels = c("Pre-Retraction", "Post-Retraction")),
      Funding = c(mean_pre, mean_post)
    )
    
    col_mean <- ifelse(mean_post < mean_pre, "#d9534f", "#005b96")
    
    p <- ggplot() +
      geom_line(data = df_long, aes(x = Period, y = Funding, group = Original_Author_Name, color = Indiv_Pct_Change_Capped,
                                    text = paste("Author:", Original_Author_Name, "<br>Period:", Period, "<br>Funding:", dollar(Funding), "<br>Change:", percent(Indiv_Pct_Change, accuracy = 0.1))), 
                alpha = 0.5, linewidth = 0.5) +
      scale_color_gradientn(colors = c("blue", "yellow", "red"),
                            values = scales::rescale(c(-1, 0, 3), from = c(-1, 3)),
                            limits = c(-1, 3),
                            labels = percent, name = "% Change") +
      geom_line(data = df_mean, aes(x = Period, y = Funding, group = 1), 
                color = "black", linewidth = 3) +
      geom_line(data = df_mean, aes(x = Period, y = Funding, group = 1), 
                color = col_mean, linewidth = 1.5) +
      geom_point(data = df_mean, aes(x = Period, y = Funding, 
                                     text = paste("Mean", Period, ":", dollar(Funding))), 
                 color = col_mean, size = 4) +
      scale_y_continuous(labels = label_dollar(), limits = c(0, NA)) +
      labs(x = "", y = "Average Annual Funding ($)") +
      dashboard_theme +
      theme(
        panel.grid.major.x = element_blank(),
        legend.position = "right"
      )
      
    ggplotly(p, tooltip = "text") %>% layout(margin = list(b = 40, t = 40, l = 10, r = 10))
  })
  
  output$plot_avg_funding_note <- renderUI({
    fa <- filtered_authors()
    total_authors <- n_distinct(fa$Original_Author_Name)
    HTML(paste0("<p style='color: gray; font-size: 12px; margin-top: 10px; font-style: italic;'>Note: The average is calculated taking into account every unique retracted author (", comma(total_authors), "). Authors receiving no funding in a given year are counted as $0, reflecting the formula: Average Funding (Year X) = Total Funding (Year X) / Total Unique Retracted Authors. To find the funding granted to retracted authors in the NIH RePORTER system, we used strict name matching (requiring an exact match of first, middle, and last names). This approach minimizes the possibility of false positives, but if an author was not found due to a name variation, they are treated as having $0 funding, making this a conservative estimate of the financial impact.</p>"))
  })
  
  # --- Statistical tests ---
  paired_data <- reactive({
    filtered_authors() %>% filter(diff_retracted >= -3 & diff_retracted <= 3 & diff_retracted != 0) %>%
      mutate(Period = ifelse(diff_retracted < 0, "Pre", "Post")) %>% group_by(Original_Author_Name, Period) %>%
      summarise(Annual_Funding = sum(Funding_Adjusted, na.rm = TRUE) / 3, Total_Grants = n_distinct(Grant_ID), .groups = "drop") %>%
      pivot_wider(names_from = Period, values_from = c(Annual_Funding, Total_Grants), values_fill = list(Annual_Funding = 0, Total_Grants = 0))
  })
  
  output$plot_pct_change_dist <- renderPlotly({
    pd <- paired_data()
    pd <- pd %>% filter(Annual_Funding_Pre > 0) %>%
      mutate(Pct_Change = (Annual_Funding_Post - Annual_Funding_Pre) / Annual_Funding_Pre) %>%
      mutate(Pct_Change_Capped = ifelse(Pct_Change > 5, 5, Pct_Change))
    
    p <- ggplot(pd, aes(x = Pct_Change_Capped)) +
      geom_histogram(fill = "#005b96", color = "white", bins = 40) +
      scale_x_continuous(labels = percent) +
      labs(x = "Individual % Change (Capped at +500%)", y = "No. of Authors") +
      dashboard_theme + theme(axis.title.y = element_blank())
      
    ggplotly(p) %>% layout(margin = list(b = 40, t = 40, l = 10, r = 10))
  })
  

  
  # --- ESTADÍSTICAS GLOBALES PARA LA FILA SUPERIOR ---
  output$stats_avg_funding <- renderUI({
    tl <- df_timeline()
    mean_pre <- mean(tl$Average_Funding_Per_Author[tl$diff_retracted %in% c(-3, -2, -1)], na.rm = TRUE)
    mean_post <- mean(tl$Average_Funding_Per_Author[tl$diff_retracted %in% c(1, 2, 3)], na.rm = TRUE)
    mean_total_pre <- mean(tl$Total_Adjusted_Funding[tl$diff_retracted %in% c(-3, -2, -1)], na.rm = TRUE)
    mean_total_post <- mean(tl$Total_Adjusted_Funding[tl$diff_retracted %in% c(1, 2, 3)], na.rm = TRUE)
    pct_change <- (mean_post - mean_pre) / mean_pre * 100
    
    # Test estadístico basado en todos los autores
    pd <- paired_data()
    test_funding <- wilcox.test(pd$Annual_Funding_Pre, pd$Annual_Funding_Post, paired = TRUE, exact = FALSE)
    pct_color <- ifelse(pct_change < 0, "#d9534f", "#5cb85c") 
    
    # Cálculos para la transición de autores
    total_authors <- n_distinct(df_authors$Original_Author_Name)
    active_authors_pre <- sum(pd$Annual_Funding_Pre > 0, na.rm = TRUE)
    active_authors_post <- sum(pd$Annual_Funding_Post > 0, na.rm = TRUE)
    lost_all_n <- sum(pd$Annual_Funding_Pre > 0 & pd$Annual_Funding_Post == 0, na.rm = TRUE)
    gained_n   <- sum(pd$Annual_Funding_Pre == 0 & pd$Annual_Funding_Post > 0, na.rm = TRUE)
    lost_all_pct <- (lost_all_n / total_authors) * 100
    gained_pct   <- (gained_n / total_authors) * 100
    
    both_funded_n  <- sum(pd$Annual_Funding_Pre > 0 & pd$Annual_Funding_Post > 0, na.rm = TRUE)
    # never_funded_n computed using sets to capture authors who might be entirely missing from pd
    never_funded_n <- total_authors - (active_authors_pre + active_authors_post - both_funded_n)
    
    HTML(paste0(
      "<div style='padding: 10px;'>",
      "<h5 style='color: #005b96; font-weight: bold; margin-bottom: 20px; text-transform: uppercase;'>3 Years Pre vs Post Retraction</h5>",
      "<div style='display: flex; justify-content: space-between; margin-bottom: 20px;'>",
      "<div style='text-align: center; width: 48%;'>",
      "<div style='font-size: 12px; color: #777; text-transform: uppercase; font-weight: bold;'>Mean Pre-Retraction</div>",
      "<div style='font-size: 24px; font-weight: bold; color: #333;'>", dollar(mean_pre, accuracy = 1), "</div>",
      "</div>",
      "<div style='text-align: center; width: 48%; border-left: 1px solid #eee;'>",
      "<div style='font-size: 12px; color: #777; text-transform: uppercase; font-weight: bold;'>Mean Post-Retraction</div>",
      "<div style='font-size: 24px; font-weight: bold; color: #333;'>", dollar(mean_post, accuracy = 1), "</div>",
      "</div>",
      "</div>",
      "<div style='text-align: center; margin-bottom: 20px;'>",
      "<span style='font-size: 14px; color: #666; text-transform: uppercase; font-weight: bold;'>Change: </span>",
      "<span style='font-size: 22px; font-weight: bold; color: ", pct_color, ";'>",
      sprintf("%+.1f%%", pct_change),
      "</span>",
      "</div>",
      
      # NUEVAS CAJAS DE TRANSICIÓN DE FONDOS
      "<div style='display: flex; justify-content: space-between; margin-bottom: 20px; font-size: 12px;'>",
      "<div style='width: 48%; background-color: #fdf2f2; padding: 10px; border-radius: 6px; border: 1px solid #fadcdc; text-align: center;'>",
      "<div style='color: #d9534f; font-weight: bold; margin-bottom: 5px;'>LOST ALL FUNDING</div>",
      "<div style='color: #777; margin-bottom: 5px;'>(Had Pre, $0 Post)</div>",
      "<div style='font-size: 18px; font-weight: bold; color: #333;'>", sprintf("%.1f%%", lost_all_pct), " <span style='font-size: 11px; font-weight: normal; color: #777;'>(", comma(lost_all_n), " authors)</span></div>",
      "</div>",
      "<div style='width: 48%; background-color: #f4fdf5; padding: 10px; border-radius: 6px; border: 1px solid #d4edda; text-align: center;'>",
      "<div style='color: #5cb85c; font-weight: bold; margin-bottom: 5px;'>GAINED FUNDING</div>",
      "<div style='color: #777; margin-bottom: 5px;'>($0 Pre, Had Post)</div>",
      "<div style='font-size: 18px; font-weight: bold; color: #333;'>", sprintf("%.1f%%", gained_pct), " <span style='font-size: 11px; font-weight: normal; color: #777;'>(", comma(gained_n), " authors)</span></div>",
      "</div>",
      "</div>",
      
      "<div style='background-color: #f8f9fa; padding: 15px; border-radius: 6px; border: 1px solid #e9ecef;'>",
      "<div style='font-size: 13px; color: #555; line-height: 1.4;'>We found that ", comma(active_authors_pre), " authors received at least some funding in the 3 years pre-retraction and ", comma(active_authors_post), " authors received at least some funding in the 3 years post-retraction. The mean total annual funding granted to these authors was ", dollar(mean_total_pre, accuracy = 1), " and ", dollar(mean_total_post, accuracy = 1), " in the pre- and post-retraction periods, respectively.</div>",
      "</div>",
      "</div>"
    ))
  })
  
  output$stats_active_grants <- renderUI({
    tl <- df_timeline()
    mean_pre <- mean(tl$Active_Grants[tl$diff_retracted %in% c(-3, -2, -1)], na.rm = TRUE)
    mean_post <- mean(tl$Active_Grants[tl$diff_retracted %in% c(1, 2, 3)], na.rm = TRUE)
    pct_change <- (mean_post - mean_pre) / mean_pre * 100
    pct_color <- ifelse(pct_change < 0, "#d9534f", "#5cb85c") 
    
    pd <- paired_data()
    test_grants <- wilcox.test(pd$Total_Grants_Pre, pd$Total_Grants_Post, paired = TRUE, exact = FALSE)
    
    HTML(paste0(
      "<div style='padding: 10px;'>",
      "<h5 style='color: #005b96; font-weight: bold; margin-bottom: 20px; text-transform: uppercase;'>3 Years Pre vs Post Retraction</h5>",
      "<div style='display: flex; justify-content: space-between; margin-bottom: 20px;'>",
      "<div style='text-align: center; width: 48%;'>",
      "<div style='font-size: 12px; color: #777; text-transform: uppercase; font-weight: bold;'>Mean Pre-Retraction</div>",
      "<div style='font-size: 24px; font-weight: bold; color: #333;'>", comma(round(mean_pre, 1)), "</div>",
      "</div>",
      "<div style='text-align: center; width: 48%; border-left: 1px solid #eee;'>",
      "<div style='font-size: 12px; color: #777; text-transform: uppercase; font-weight: bold;'>Mean Post-Retraction</div>",
      "<div style='font-size: 24px; font-weight: bold; color: #333;'>", comma(round(mean_post, 1)), "</div>",
      "</div>",
      "</div>",
      "<div style='text-align: center; margin-bottom: 25px;'>",
      "<span style='font-size: 14px; color: #666; text-transform: uppercase; font-weight: bold;'>Change: </span>",
      "<span style='font-size: 22px; font-weight: bold; color: ", pct_color, ";'>",
      sprintf("%+.1f%%", pct_change),
      "</span>",
      "</div>",
      "</div>"
    ))
  })
  
  output$stats_total_funding <- renderUI({
    tl <- df_timeline()
    mean_pre <- mean(tl$Total_Adjusted_Funding[tl$diff_retracted %in% c(-3, -2, -1)], na.rm = TRUE)
    mean_post <- mean(tl$Total_Adjusted_Funding[tl$diff_retracted %in% c(1, 2, 3)], na.rm = TRUE)
    pct_change <- (mean_post - mean_pre) / mean_pre * 100
    test_funding <- wilcox.test(paired_data()$Annual_Funding_Pre, paired_data()$Annual_Funding_Post, paired = TRUE, exact = FALSE)
    pct_color <- ifelse(pct_change < 0, "#d9534f", "#5cb85c") 
    
    HTML(paste0(
      "<div style='padding: 10px;'>",
      "<h5 style='color: #005b96; font-weight: bold; margin-bottom: 20px; text-transform: uppercase;'>3 Years Pre vs Post Retraction</h5>",
      "<div style='display: flex; justify-content: space-between; margin-bottom: 20px;'>",
      "<div style='text-align: center; width: 48%;'>",
      "<div style='font-size: 12px; color: #777; text-transform: uppercase; font-weight: bold;'>Mean Pre-Retraction</div>",
      "<div style='font-size: 24px; font-weight: bold; color: #333;'>", dollar(mean_pre, accuracy = 1), "</div>",
      "</div>",
      "<div style='text-align: center; width: 48%; border-left: 1px solid #eee;'>",
      "<div style='font-size: 12px; color: #777; text-transform: uppercase; font-weight: bold;'>Mean Post-Retraction</div>",
      "<div style='font-size: 24px; font-weight: bold; color: #333;'>", dollar(mean_post, accuracy = 1), "</div>",
      "</div>",
      "</div>",
      "<div style='text-align: center; margin-bottom: 25px;'>",
      "<span style='font-size: 14px; color: #666; text-transform: uppercase; font-weight: bold;'>Change: </span>",
      "<span style='font-size: 22px; font-weight: bold; color: ", pct_color, ";'>",
      sprintf("%+.1f%%", pct_change),
      "</span>",
      "</div>",
      "</div>"
    ))
  })
  

  
}

# 5. RUN APP
# ------------------------------------------------------------------------------
shinyApp(ui = ui, server = server)