# ==============================================================================
# SHINY DASHBOARD: NIH Retraction Cost 
# ==============================================================================
# Reads three pre-processed CSVs that the Python pipeline produces and renders
# a multi-tab dashboard. CPI data is loaded from a cached CSV (annual_cpi.csv)
# regenerated by the weekly pipeline; this avoids a network call to FRED on
# every cold start of the app on shinyapps.io.
# ==============================================================================

# 1. LIBRARIES & GLOBAL SETUP
# ------------------------------------------------------------------------------
library(shiny)
library(tidyverse)
library(scales)
library(lubridate)
library(DT)
library(plotly)
library(shinycssloaders)

# --- INPUT FILES ---
papers_file  <- "data/processed/FINAL_Retractions_Costs_and_Pubs.csv"
authors_file <- "data/processed/Author_Funding_Matches.csv"
cpi_file     <- "data/processed/annual_cpi.csv"
grant_keep_file <- "data/processed/author_grant_keep.csv"  # built by build_collision_flags.R

# --- ANNUAL CPI ---
# Primary source: cached CSV produced by src/cpi_fetcher.py (weekly cron).
# Fallback (only if the CSV is missing): live FRED pull via quantmod, kept as a
# safety net so the app still works in a fresh local clone.
load_annual_cpi <- function(path = cpi_file) {
  
  if (file.exists(path)) {
    df <- readr::read_csv(path, show_col_types = FALSE)
    if (!"Inflation_Multiplier" %in% colnames(df)) {
      current_cpi <- max(df$CPI, na.rm = TRUE)
      df$Inflation_Multiplier <- current_cpi / df$CPI
    }
    return(df[, c("Fiscal_Year", "CPI", "Inflation_Multiplier")])
  }
  
  warning(
    "annual_cpi.csv not found; falling back to live FRED download. ",
    "Run `python -m src.cpi_fetcher` to generate the cache."
  )
  
  if (!requireNamespace("quantmod", quietly = TRUE)) {
    install.packages("quantmod", repos = "https://cloud.r-project.org")
  }
  
  cpi_xts <- quantmod::getSymbols("CPIAUCSL", src = "FRED", auto.assign = FALSE)
  monthly <- data.frame(Date = zoo::index(cpi_xts), CPI = as.numeric(cpi_xts))
  annual <- monthly %>%
    mutate(Fiscal_Year = lubridate::year(Date)) %>%
    group_by(Fiscal_Year) %>%
    summarise(CPI = mean(CPI, na.rm = TRUE), .groups = "drop")
  
  current_cpi <- max(annual$CPI, na.rm = TRUE)
  annual %>% mutate(Inflation_Multiplier = current_cpi / CPI)
}

annual_cpi <- load_annual_cpi()

# --- LOAD PAPERS ---
df_papers <- read_csv(papers_file, show_col_types = FALSE) %>%
  mutate(
    Publication_Year = as.numeric(str_extract(OriginalPaperDate, "(?<=/)\\d{4}")),
    Retraction_Year  = as.numeric(str_extract(RetractionDate,    "(?<=/)\\d{4}")),
    retraction_lag   = Retraction_Year - Publication_Year,
    # Single source of truth: a paper is "NIH Funded" if it has any positive NIH funding.
    Funding_Status   = ifelse(!is.na(Total_NIH_Funding_Cost) & Total_NIH_Funding_Cost > 0,
                              "NIH Funded", "Not NIH Funded / Other"),
    attributed_cost_raw = ifelse(
      !is.na(Total_Grant_Pubs) & Total_Grant_Pubs > 0,
      Total_NIH_Funding_Cost / Total_Grant_Pubs,
      NA
    )
  ) %>%
  left_join(annual_cpi, by = c("Publication_Year" = "Fiscal_Year")) %>%
  mutate(attributed_cost_adjusted = attributed_cost_raw * Inflation_Multiplier)

# Helper: data-driven y-axis limits starting at zero (top-padded so points don't touch frame)
add_margin <- function(v, pad = 0.10) {
  c(0, max(v, na.rm = TRUE) * (1 + pad))
}

# Helper: abbreviated dollar formatter (e.g., $1.23B, $755K)
dollar_short <- scales::label_dollar(accuracy = 0.01, scale_cut = scales::cut_short_scale())

# Helper: format p-values for inline reporting
fmt_p <- function(p) {
  if (is.na(p)) return("NA")
  if (p < 0.001) "p &lt; 0.001" else sprintf("p = %.3f", p)
}

# --- LOAD AUTHORS ---
df_authors_raw <- read_csv(authors_file, show_col_types = FALSE)

author_retractions <- df_authors_raw %>%
  group_by(Original_Author_Name) %>%
  summarise(Num_Retractions = n_distinct(Record_ID), .groups = "drop")

# Grant-level name-collision filter (built by build_collision_flags.R), matching the manuscript.
# Common author names can match the grant records of several different NIH investigators; for an
# author whose name collides with more than one investigator we keep only the grants belonging to
# the real person's PI_ID (anchored by the institution on their retracted paper; PI_ID is stable
# across institution moves) and drop grants held by same-named others. Non-collision authors keep
# every grant. If the artefact is missing, fall back to no filtering so the app still runs.
grant_keep <- tryCatch(read_csv(grant_keep_file, show_col_types = FALSE),
                       error = function(e) NULL)

df_authors <- df_authors_raw %>%
  group_by(Original_Author_Name) %>%
  mutate(First_Retraction_Year = min(Retraction_Year, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(diff_retracted = Fiscal_Year - First_Retraction_Year)

# Apply the grant-level collision filter (drop grants belonging to same-named other investigators)
# before collapsing to distinct author-grant-year rows. Skipped if the artefact is unavailable.
if (!is.null(grant_keep)) {
  df_authors <- df_authors %>%
    left_join(grant_keep, by = c("Original_Author_Name", "Grant_ID")) %>%
    filter(coalesce(keep_consequences, TRUE))
}

df_authors <- df_authors %>%
  distinct(Original_Author_Name, First_Retraction_Year, Grant_ID, Fiscal_Year, Funding_Amount, diff_retracted) %>%
  left_join(annual_cpi, by = "Fiscal_Year") %>%
  mutate(Funding_Adjusted = Funding_Amount * Inflation_Multiplier) %>%
  left_join(author_retractions, by = "Original_Author_Name")

# Restrict the author-consequences cohort to authors whose first retraction is early
# enough that a full +3-year post-retraction window is observable given the latest
# fiscal year available in RePORTER. Without this restriction, authors retracted in
# the last 3 years contribute $0 to post-retraction offsets for years that have not
# yet happened, artificially inflating the apparent funding drop.
latest_fiscal_year     <- max(df_authors$Fiscal_Year, na.rm = TRUE)
retraction_cutoff_year <- latest_fiscal_year - 3
df_authors <- df_authors %>% filter(First_Retraction_Year <= retraction_cutoff_year)

# --- GRANT-LEVEL DIRECT COST (Summary tab) ---
# Mirrors the "Direct cost to the NIH" section of policy_analysis.qmd. Two measures beyond the
# per-paper attributed cost:
#   (2) total_cost_unique_grants -> full nominal award of every DISTINCT NIH grant behind a
#       retracted paper, counted once (a grant can yield several retracted papers, so summing
#       across paper rows would double-count shared grants).
#   (4) total_cost_personal_pi   -> of those distinct grants, only investigator-held
#       research/career/fellowship awards (codes R/K/F + DP1/2/5) for which a retracted author is
#       the PI. Excludes institutional center/infrastructure funding (P30, U01, P01, training...).
cpi_year <- max(annual_cpi$Fiscal_Year, na.rm = TRUE)

# (2) Distinct-grant nominal cost, no double counting. Funding_Info_cleaned (grant IDs) and
# Individual_NIH_Grant_Costs (matching awards) are ";"-separated, aligned position-for-position.
grant_costs <- df_papers %>%
  filter(Funding_Status == "NIH Funded") %>%
  transmute(mult = Inflation_Multiplier,
            pair = map2(str_split(Funding_Info_cleaned, ";"),
                        str_split(Individual_NIH_Grant_Costs, ";"),
                        ~ tibble(grant = str_trim(.x), gcost = as.numeric(str_trim(.y))))) %>%
  unnest(pair) %>%
  filter(!is.na(grant), grant != "", !is.na(gcost)) %>%
  # Collapse to one row per DISTINCT grant: gcost = first() (a grant carries the same award in
  # every paper citing it); mult = mean() of the citing papers' CPI multipliers (a grant has no
  # single base year to deflate from).
  group_by(grant) %>% summarise(gcost = first(gcost), mult = mean(mult, na.rm = TRUE), .groups = "drop")
mult_fallback <- mean(grant_costs$mult[is.finite(grant_costs$mult)])
grant_costs   <- grant_costs %>% mutate(mult = ifelse(is.finite(mult), mult, mult_fallback))
n_unique_grants          <- nrow(grant_costs)
total_cost_unique_grants <- sum(grant_costs$gcost)

# (3) Recover each grant's NIH activity code (R01, P30, ...) to flag "personal" investigator awards.
# The code is not in Funding_Info_cleaned but is in the raw Funding_Info text (e.g. "(R01 CA203737)")
# and in the authors file's full Grant_ID (e.g. "K08HL086671"). Prefer Funding_Info, else authors.
code_pat <- "([A-Z][A-Z0-9]{2})\\s*([A-Z]{2})([0-9]{4,})"
fi_map <- df_papers %>% filter(Funding_Status == "NIH Funded") %>%
  transmute(m = str_match_all(Funding_Info, code_pat)) %>%
  mutate(p = map(m, ~ tibble(grant = paste0(.x[, 3], .x[, 4]), act = .x[, 2]))) %>%
  select(p) %>% unnest(p) %>%
  distinct(grant, act) %>% group_by(grant) %>% summarise(act_fi = first(act), .groups = "drop")
au_map <- df_authors_raw %>%
  transmute(m = str_match(Grant_ID, code_pat)) %>%
  transmute(grant = paste0(m[, 3], m[, 4]), act = m[, 2]) %>%
  filter(!is.na(act)) %>% distinct(grant, act) %>%
  group_by(grant) %>% summarise(act_au = first(act), .groups = "drop")
grants_typed <- grant_costs %>%
  left_join(fi_map, by = "grant") %>% left_join(au_map, by = "grant") %>%
  mutate(activity = toupper(coalesce(act_fi, act_au)),
         personal = coalesce((str_detect(activity, "^[RKF]") &
                              !activity %in% c("K12", "KL2", "R24", "R25", "R41", "R42", "R43", "R44", "RL1")) |
                             activity %in% c("DP1", "DP2", "DP5"), FALSE))

# (4) Keep only the personal grants for which a retracted author is the PI (grant "core" = IC +
# serial appears in the author-funding matches, i.e. the retracted author holds it, not merely
# acknowledged). These are investigator-held, PI-attributed dollars.
pi_cores <- df_authors_raw %>%
  transmute(core = str_extract(Grant_ID, "[A-Z]{2}[0-9]{4,}$")) %>%
  filter(!is.na(core)) %>% distinct(core) %>% pull(core)
personal_pi <- grants_typed$personal & grants_typed$grant %in% pi_cores
total_cost_personal_pi     <- sum(grants_typed$gcost[personal_pi])                        # nominal $
total_cost_personal_pi_adj <- sum((grants_typed$gcost * grants_typed$mult)[personal_pi])  # CPI-adjusted $
n_grants_personal_pi       <- sum(personal_pi)

# --- GLOBAL PLOT THEME ---
# Transparent backgrounds so plots blend with the dashboard cards.
dashboard_theme <- theme_classic(base_size = 12) +
  theme(
    legend.position  = "top",
    legend.title     = element_blank(),
    plot.background  = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA),
    panel.grid.major.y = element_line(color = "gray90", linewidth = 0.5)
  )

corporate_colors <- c("NIH Funded" = "#005b96",
                      "Not NIH Funded / Other" = "gray70")

# Finalize a paper-level card plot (Article Characteristics tab). On shinyapps.io plotly can
# mis-size a ggplotly rendered inside an initially-hidden / narrow tab, leaving the panel shifted
# to the right. Forcing a full x-domain, an explicit/auto left margin, a left-anchored top legend
# (no negative-x reservation) and responsive sizing -- together with the tab-shown resize hook in
# the header -- keeps every plot filling its card. `left` is the base left margin; automargin
# expands it for the horizontal bar charts whose category labels need more room.
finalize_card_plot <- function(gg, left = 55) {
  ggplotly(gg, tooltip = c("x", "y", "fill")) %>%
    layout(legend = list(orientation = "h", x = 0, xanchor = "left", y = 1.12, title = list(text = "")),
           margin = list(l = left, r = 25, t = 55, b = 45),
           xaxis = list(domain = c(0, 1), automargin = TRUE),
           yaxis = list(automargin = TRUE),
           autosize = TRUE) %>%
    config(responsive = TRUE)
}

# --- Figure-1-style within-author difference boxplots (shared logic with policy_analysis.qmd) -
# For each author and year offset, the change in value (funding $ or active-grant count) vs.
# that author's value at year -3 (a within-author subtraction, defined for the full cohort;
# year -3 is identically 0). Drawn as a decomposed boxplot coloured by period.
make_diff_box_data <- function(per_author_value, cohort_names, value_col = "Annual_Funding") {
  grid <- tidyr::crossing(Original_Author_Name = cohort_names, diff_retracted = -3:3) %>%
    left_join(per_author_value, by = c("Original_Author_Name", "diff_retracted")) %>%
    mutate(.val = ifelse(is.na(.data[[value_col]]), 0, .data[[value_col]]))
  baseline <- grid %>% filter(diff_retracted == -3) %>% transmute(Original_Author_Name, Baseline = .val)
  grid %>% left_join(baseline, by = "Original_Author_Name") %>%
    mutate(Funding_Diff = .val - Baseline)
}
box_stats <- function(box_data) box_data %>%
  group_by(diff_retracted) %>%
  summarise(p10 = quantile(Funding_Diff, 0.10), p25 = quantile(Funding_Diff, 0.25),
            p50 = median(Funding_Diff), p75 = quantile(Funding_Diff, 0.75),
            p90 = quantile(Funding_Diff, 0.90), .groups = "drop")
mean_line <- function(box_data) box_data %>%
  group_by(diff_retracted) %>% summarise(Funding_Diff = mean(Funding_Diff), .groups = "drop")
# Tight y-axis fit to the visible whiskers (10th-90th pct) + mean, small 5% margin.
whisker_cap <- function(stat_data, mean_data) {
  lo <- min(c(stat_data$p10, mean_data$Funding_Diff), na.rm = TRUE)
  hi <- max(c(stat_data$p90, mean_data$Funding_Diff), na.rm = TRUE)
  pad <- 0.05 * (hi - lo); if (!is.finite(pad) || pad == 0) pad <- 1
  c(lo - pad, hi + pad)
}
# Decomposed boxplot (no box outline): green = pre-retraction (-3..0), orange = post (1..3),
# with the mean change overlaid as a black line + points. Returns a ggplot for ggplotly.
make_box_panel_app <- function(stat_data, mean_data, y_cap, y_label, dollar_y = TRUE) {
  period_pal <- c("Pre-retraction" = "#00716f", "Post-retraction" = "#d16b2a")
  bw <- 0.6
  fmt <- if (dollar_y) function(x) dollar(x, accuracy = 1) else function(x) comma(x, accuracy = 0.1)
  stat_data <- stat_data %>% mutate(
    Period2 = factor(ifelse(diff_retracted <= 0, "Pre-retraction", "Post-retraction"),
                     levels = c("Pre-retraction", "Post-retraction")),
    text = paste0("Year offset: ", diff_retracted, "<br>Median: ", fmt(p50),
                  "<br>IQR: ", fmt(p25), " to ", fmt(p75),
                  "<br>10th-90th pct: ", fmt(p10), " to ", fmt(p90)))
  mean_data <- mean_data %>% mutate(
    text = paste0("Year offset: ", diff_retracted, "<br>Mean change: ", fmt(Funding_Diff)))
  ggplot(stat_data, aes(x = diff_retracted)) +
    geom_vline(xintercept = 0, color = "#d9534f", linetype = "dashed", linewidth = 0.8) +
    geom_errorbar(aes(ymin = p10, ymax = p90), width = 0.3, linewidth = 0.4, color = "gray30") +
    geom_tile(aes(y = (p25 + p75) / 2, height = p75 - p25, fill = Period2, text = text),
              width = bw, color = NA) +
    geom_segment(aes(x = diff_retracted - bw / 2, xend = diff_retracted + bw / 2, y = p50, yend = p50),
                 color = "gray30", linewidth = 0.5) +
    geom_line(data = mean_data, aes(x = diff_retracted, y = Funding_Diff), color = "black", linewidth = 0.8, group = 1) +
    geom_point(data = mean_data, aes(x = diff_retracted, y = Funding_Diff, text = text), color = "black", size = 2) +
    scale_fill_manual(values = period_pal, breaks = c("Pre-retraction", "Post-retraction")) +
    scale_x_continuous(breaks = -3:3) +
    scale_y_continuous(labels = if (dollar_y) label_dollar() else label_number(accuracy = 1)) +
    coord_cartesian(ylim = y_cap) +
    labs(x = "Years from First Retraction", y = y_label, fill = NULL) +
    dashboard_theme +
    theme(axis.line.y = element_blank(), axis.ticks.y = element_blank(),
          panel.grid.major.x = element_blank())
}

# Inline HTML reporting of a test statistic with its p-value (congruent with policy_analysis.qmd).
wilcox_txt  <- function(t) paste0("<i>V</i> = ", comma(round(unname(t$statistic))), ", ", fmt_p(t$p.value))
mcnemar_txt <- function(t) paste0("&chi;&sup2;(", unname(t$parameter), ") = ",
                                  sprintf("%.1f", unname(t$statistic)), ", ", fmt_p(t$p.value))

# Broad reason categories, identical to policy_analysis.qmd / supplementary_materials.qmd.
reason_clusters <- list(
  "Image duplication / manipulation"       = c("Duplication of/in Image", "Manipulation of Images", "Falsification/Fabrication of Image", "Concerns/Issues about Image", "Plagiarism of Image", "Unreliable Image"),
  "Formal misconduct investigation"        = c("Investigation by Company/Institution", "Investigation by ORI", "Investigation by Third Party", "Misconduct - Official Investigation(s) and/or Finding(s)", "Misconduct by Author", "Falsification/Fabrication of Data", "Falsification/Fabrication of Results"),
  "Reliability / reproducibility concerns" = c("Unreliable Results and/or Conclusions", "Unreliable Data", "Concerns/Issues about Data", "Concerns/Issues about Results and/or Conclusions", "Results Not Reproducible", "Original Data and/or Images not Provided and/or not Available"),
  "Plagiarism / duplicate publication"     = c("Plagiarism of/in Article", "Plagiarism of Text", "Plagiarism of Data", "Duplication of/in Article", "Duplication of Text", "Euphemisms for Plagiarism", "Euphemisms for Duplication", "Duplication of Data"),
  "Honest error"                           = c("Error in Data", "Error in Analyses", "Error in Results and/or Conclusions", "Error in Methods", "Error in Image"),
  "Paper mill / compromised peer review / AI generated content" = c("Compromised Peer Review", "Concerns/Issues about Peer Review", "Paper Mill", "False/Forged Authorship", "False/Forged Affiliation", "Computer-Aided Content or Computer-Generated Content")
)
reason_cat_map <- tibble(Reason = unlist(reason_clusters, use.names = FALSE),
                         Category = rep(names(reason_clusters), lengths(reason_clusters)))


# 2. CUSTOM CSS (NIH RePORTER look-alike)
# ------------------------------------------------------------------------------
nih_css <- "
  /* Light gray page background */
  body { background-color: #f4f6f9; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; }

  /* Dark top navbar */
  .navbar-inverse { background-color: #2b2b2b; border-color: #1a1a1a; }
  .navbar-inverse .navbar-brand { color: #ffffff; font-weight: bold; font-size: 22px; }
  .navbar-inverse .navbar-nav>li>a { color: #dddddd; font-weight: bold; }
  .navbar-inverse .navbar-nav>li>a:hover { color: #ffffff; }

  /* NIH-style hero banner with blue/teal gradient */
  .hero-banner {
    background: linear-gradient(135deg, #09375e 0%, #13778a 100%);
    color: white;
    padding: 40px 30px;
    margin-top: -20px; /* pull flush against the navbar */
    margin-bottom: 30px;
    margin-left: -15px;
    margin-right: -15px;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
  }
  .hero-banner h2 { margin-top: 0; font-weight: bold; }
  .kpi-box {
    background: rgba(255, 255, 255, 0.15);
    border: 1px solid rgba(255, 255, 255, 0.3);
    border-radius: 5px;
    padding: 15px;
    text-align: center;
    word-wrap: break-word;
    overflow-wrap: break-word;
  }
  .kpi-box h3 { margin: 0; font-size: clamp(16px, 2.5vw, 28px); font-weight: bold; }
  .kpi-box p { margin: 0; font-size: 14px; text-transform: uppercase; }

  /* White cards with a teal top border */
  .nih-card {
    background: white;
    border-radius: 4px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    border-top: 4px solid #17a2b8;
    padding: 20px;
    margin-bottom: 25px;
  }
  .nih-card h4 {
    color: #333;
    font-weight: bold;
    margin-top: 0;
    margin-bottom: 20px;
    font-size: 18px;
  }

  /* Page footer (shown below the tab content on every tab) */
  .dashboard-footer {
    margin-top: 30px;
    padding: 22px 15px 26px 15px;
    text-align: center;
    color: #777;
    font-size: 13px;
    line-height: 1.7;
    border-top: 1px solid #dcdcdc;
  }
  .dashboard-footer a { color: #17a2b8; text-decoration: none; font-weight: bold; }
  .dashboard-footer a:hover { text-decoration: underline; }
"

# 3. USER INTERFACE (UI)
# ------------------------------------------------------------------------------
mtime_val <- file.info(papers_file)$mtime
months_eng <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
last_updated_str <- paste0(months_eng[as.integer(format(mtime_val, "%m"))], " ", format(mtime_val, "%d, %Y"))

ui <- navbarPage(
  title = "NIH Retraction Cost Dashboard",
  inverse = TRUE,
  header = tags$head(
    tags$style(HTML(nih_css)),
    tags$script(HTML(sprintf("
      $(document).ready(function() {
        $('<p class=\"navbar-text navbar-right\" style=\"margin-right: 15px; color: #dddddd;\">Last updated: %s</p>').appendTo('.navbar > .container-fluid');
      });
    ", last_updated_str))),
    # Plotly plots on non-active tabs are laid out inside a hidden container and can render at the
    # wrong width on shinyapps.io (they appear shifted to the right). Force every plotly plot to
    # recompute its size when its tab is shown (and shortly after load), directly via
    # Plotly.Plots.resize plus a window resize event. No effect locally (already correct).
    tags$script(HTML("
      function ccResizePlots() {
        if (window.Plotly && window.Plotly.Plots) {
          document.querySelectorAll('.js-plotly-plot').forEach(function(gd) {
            try { window.Plotly.Plots.resize(gd); } catch (e) {}
          });
        }
        window.dispatchEvent(new Event('resize'));
      }
      $(document).on('shown.bs.tab', function() {
        setTimeout(ccResizePlots, 50);
        setTimeout(ccResizePlots, 350);
      });
      $(window).on('load', function() { setTimeout(ccResizePlots, 350); });
    "))
  ),
  
  # --- TAB 1: Summary ---
  tabPanel("Summary Stats",
           fluidRow(
             column(12,
                    div(class = "hero-banner",
                        fluidRow(
                          column(4,
                                 h2("Welcome to the NIH Retraction Cost Dashboard"),
                                 p("Analyzing the financial footprint of U.S. retracted research funded by the NIH.")
                          ),
                          column(8,
                                 fluidRow(
                                   column(4, div(class = "kpi-box", p("U.S. Retracted Papers"), h3(textOutput("kpi_papers")))),
                                   column(4, div(class = "kpi-box", p("NIH Funded"), h3(textOutput("kpi_nih_papers")))),
                                   column(4, div(class = "kpi-box", p("Adj. Funding Lost"), h3(textOutput("kpi_funding"))))
                                 )
                          )
                        )
                    )
             )
           ),
           fluidPage(
             fluidRow(
               column(12,
                      div(class = "nih-card",
                          h4("Retraction Costs Summary (Raw and FRED CPI Adjusted)"),
                          withSpinner(DTOutput("cost_summary_table"), type = 4, color = "#17a2b8"),
                          p(em("Note: Adjusted Attributed Cost reflects values adjusted for inflation to current dollars using the Consumer Price Index for All Urban Consumers (CPI-AUCSL) provided by the Federal Reserve Economic Data (FRED)."),
                            style = "color: gray; font-size: 12px; margin-top: 10px;"),
                          # Grant-level funding behind retracted papers (distinct grants + investigator-held
                          # R/K/F PI awards), mirroring the "Direct cost to the NIH" section of the manuscript.
                          # Values are computed once at startup in the grant-level cost block above.
                          div(style = "background-color: #f8f9fa; padding: 15px; border-radius: 6px; border: 1px solid #e9ecef; margin-top: 20px;",
                              div(style = "font-size: 14px; color: #555; line-height: 1.5;",
                                  HTML(paste0(
                                    "The retracted publications were associated with a total of ", comma(n_unique_grants),
                                    " distinct NIH grants, i.e., a total of ", dollar_short(total_cost_unique_grants),
                                    " in nominal dollars. However, the vast majority of this sum is institutional center and infrastructure funding (e.g., P30 center core grants) rather than money awarded to individual investigators. Considering only investigator-held research, career and fellowship awards (R/K/F-series) for which the retracted author was the principal investigator, a total amount of ",
                                    dollar_short(total_cost_personal_pi), " in nominal dollars (", dollar_short(total_cost_personal_pi_adj),
                                    " in ", cpi_year, " dollars) from ", comma(n_grants_personal_pi),
                                    " grants was associated with retracted papers."
                                  ))
                              )
                          )
                      )
               )
             )
           )
  ),
  
  # --- TAB 2: Article Characteristics ---
  tabPanel("Article Characteristics",
           fluidPage(
             br(),
             fluidRow(
               column(6, div(class = "nih-card", h4("Publication Year"), withSpinner(plotlyOutput("plot_pub_year"), type = 4, color = "#17a2b8"))),
               column(6, div(class = "nih-card", h4("Retraction Year"), withSpinner(plotlyOutput("plot_ret_year"), type = 4, color = "#17a2b8")))
             ),
             fluidRow(
               column(8, offset = 2, div(class = "nih-card",
                             h4("Lag Between Publication and Retraction"),
                             withSpinner(plotlyOutput("plot_retraction_lag"), type = 4, color = "#17a2b8"),
                             uiOutput("lag_note")))
             ),
             fluidRow(
               column(6, div(class = "nih-card", h4("Top Reasons for Retraction"),
                             withSpinner(plotlyOutput("plot_reasons"), type = 4, color = "#17a2b8"),
                             p(em("Note: The percentages are the share of papers in each funding group (NIH-funded, in blue; non-NIH-funded, in gray) whose retraction notice lists a reason in that category. Because a paper can list several reasons, the categories are not mutually exclusive and the percentages do not sum to 100%."),
                               style = "color: gray; font-size: 12px; margin-top: 10px;"))),
               column(6, div(class = "nih-card",
                             h4("Scientific Domains"),
                             withSpinner(plotlyOutput("plot_domains"), type = 4, color = "#17a2b8"),
                             p(em("Note: The percentages are the share of papers in each funding group (NIH-funded, in blue; non-NIH-funded, in gray) classified in that scientific domain. A single paper can have multiple subjects, but each broad category is counted at most once per paper. Because a paper can span several domains, the categories are not mutually exclusive and the percentages do not sum to 100%."),
                               style = "color: gray; font-size: 12px; margin-top: 10px;")))
             ),
             fluidRow(
               column(8, offset = 2, div(class = "nih-card",
                              h4("Top Retracted Publishers"),
                              withSpinner(plotlyOutput("plot_publishers", height = "560px"), type = 4, color = "#17a2b8"),
                              p(em("Note: Publishers were grouped by parent companies where possible. 'Springer Nature' includes Springer, Nature, BMC, Palgrave. 'Elsevier' includes Cell Press, Lancet. 'Hindawi' has been separated from 'Wiley' to show its specific impact. 'Taylor & Francis' includes Routledge, Dove Medical Press."),
                                style = "color: gray; font-size: 12px; margin-top: 10px;")))
             )
           )
  ),
  
  # --- TAB 3: Author consequences ---
  tabPanel("Author consequences",
           fluidPage(
             br(),
             fluidRow(
               column(8, p(HTML(paste0(strong("Note:"), " The charts below show CPI-adjusted NIH funding and activity for authors who had a paper retracted. Data is grouped by year offset relative to each author's first retraction (year 0). The cohort is restricted to authors whose first retraction occurred by ", retraction_cutoff_year, " so that a full 3-year post-retraction window of funding data is observable for every author given the most recent RePORTER fiscal year (", latest_fiscal_year, ").")),
                            style = "color: gray; font-style: italic; margin-bottom: 20px;")),
               column(4, selectInput("author_cohort_filter", HTML("<span style='white-space: nowrap;'>Sensitivity Analysis (Retracted Papers per Author):</span>"), 
                                     choices = c("All Authors" = "all", "1 Paper Retracted" = "one", ">1 Papers Retracted" = "more"),
                                     selected = "all", width = "100%"))
             ),
             fluidRow(
               column(6, div(class = "nih-card",
                             h4("Change in Annual NIH Funding vs. Year -3"),
                             withSpinner(plotlyOutput("plot_avg_funding"), type = 4, color = "#17a2b8"),
                             uiOutput("plot_avg_funding_note"))),
               column(6, div(class = "nih-card",
                             h4("Average Funding Statistics"),
                             withSpinner(uiOutput("stats_avg_funding"), type = 4, color = "#17a2b8")))
             ),
             fluidRow(
               column(6, div(class = "nih-card",
                             h4("Change in Active NIH Grants vs. Year -3"),
                             withSpinner(plotlyOutput("plot_active_grants"), type = 4, color = "#17a2b8"),
                             p(em("Note: Because multiple retracted authors can be funded by the exact same NIH grant (e.g., as co-investigators), the total distinct grants across subgroups will not sum perfectly to the overall 'All Authors' total due to these shared grants being counted in both groups."), style = "color: gray; font-size: 12px; margin-top: 10px;"))),
               column(6, div(class = "nih-card",
                             h4("Active Grants Statistics"),
                             withSpinner(uiOutput("stats_active_grants"), type = 4, color = "#17a2b8")))
             )
           )
  ),
  footer = tags$footer(
    class = "dashboard-footer",
    HTML(paste0(
      "2026 &middot; <a href='https://sandovallentisco.github.io/' target='_blank' rel='noopener'>Alejandro Sandoval-Lentisco</a><br>",
      "Details about the methodology can be found in <em>Sandoval-Lentisco, A., Ioannidis, J.P.A. (2026). Cost of Retracted Articles to the NIH: a Living Analysis. medRxiv</em>.<br>",
      "Data and analysis code can be found at <a href='https://github.com/sandovallentisco/nih-retractions-cost' target='_blank' rel='noopener'>github.com/sandovallentisco/nih-retractions-cost</a>."
    ))
  )
)

# 4. SERVER LOGIC
# ------------------------------------------------------------------------------
server <- function(input, output, session) {
  
  # --- KPI tiles ---
  output$kpi_papers <- renderText({ comma(nrow(df_papers)) })
  output$kpi_funding <- renderText({ dollar(sum(df_papers$attributed_cost_adjusted, na.rm = TRUE), accuracy = 1) })
  output$kpi_nih_papers <- renderText({ comma(sum(df_papers$Funding_Status == "NIH Funded")) })
  
  # --- Summary table ---
  output$cost_summary_table <- renderDT({
    cost_summary_df <- data.frame(
      Metric = c("Mean", "Median", "Q1", "Q3", "Total Funding Lost"),
      Raw_Attributed_Cost = c(
        mean(df_papers$attributed_cost_raw, na.rm = TRUE), median(df_papers$attributed_cost_raw, na.rm = TRUE),
        quantile(df_papers$attributed_cost_raw, 0.25, na.rm = TRUE), quantile(df_papers$attributed_cost_raw, 0.75, na.rm = TRUE),
        sum(df_papers$attributed_cost_raw, na.rm = TRUE)
      ),
      Adjusted_Cost_Current = c(
        mean(df_papers$attributed_cost_adjusted, na.rm = TRUE), median(df_papers$attributed_cost_adjusted, na.rm = TRUE),
        quantile(df_papers$attributed_cost_adjusted, 0.25, na.rm = TRUE), quantile(df_papers$attributed_cost_adjusted, 0.75, na.rm = TRUE),
        sum(df_papers$attributed_cost_adjusted, na.rm = TRUE)
      )
    ) %>%
      mutate(
        Raw_Attributed_Cost   = dollar(Raw_Attributed_Cost,   accuracy = 1),
        Adjusted_Cost_Current = dollar(Adjusted_Cost_Current, accuracy = 1)
      ) %>%
      rename(
        `Raw Attributed Cost` = Raw_Attributed_Cost,
        `Adjusted Attributed Cost` = Adjusted_Cost_Current
      )
    
    datatable(cost_summary_df,
              class = 'row-border',
              selection = 'none',
              options = list(dom = 't', ordering = FALSE, paging = FALSE),
              rownames = FALSE)
  })
  
  # --- Paper-level plots (Plotly) ---
  output$plot_pub_year <- renderPlotly({
    p <- df_papers %>% drop_na(Publication_Year) %>% filter(Publication_Year >= 1970) %>%
      rename(`Publication Year` = Publication_Year, `Funding Status` = Funding_Status) %>%
      count(`Publication Year`, `Funding Status`, name = "No. of articles") %>%
      ggplot(aes(x = `Publication Year`, y = `No. of articles`, fill = `Funding Status`)) +
      geom_col(width = 1, color = "white", position = "stack") +
      scale_fill_manual(values = corporate_colors) +
      scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
      labs(x = "Publication Year", y = "No. of articles") + dashboard_theme
    finalize_card_plot(p)
  })
  
  output$plot_ret_year <- renderPlotly({
    p <- df_papers %>% drop_na(Retraction_Year) %>% filter(Retraction_Year >= 1970) %>%
      rename(`Retraction Year` = Retraction_Year, `Funding Status` = Funding_Status) %>%
      count(`Retraction Year`, `Funding Status`, name = "No. of articles") %>%
      ggplot(aes(x = `Retraction Year`, y = `No. of articles`, fill = `Funding Status`)) +
      geom_col(width = 1, color = "white", position = "stack") +
      scale_fill_manual(values = corporate_colors) +
      scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
      labs(x = "Retraction Year", y = "No. of articles") + dashboard_theme
    finalize_card_plot(p)
  })
  
  # --- Retraction-lag histogram + summary ---
  LAG_AXIS_MAX <- 25
  
  lag_diagnostics <- reactive({
    n_total    <- nrow(df_papers)
    n_missing  <- sum(is.na(df_papers$retraction_lag))
    n_negative <- sum(df_papers$retraction_lag < 0, na.rm = TRUE)
    valid      <- df_papers %>% filter(!is.na(retraction_lag) & retraction_lag >= 0)
    n_outliers <- sum(valid$retraction_lag > LAG_AXIS_MAX, na.rm = TRUE)
    list(total = n_total, missing = n_missing, negative = n_negative, outliers = n_outliers, valid = valid)
  })
  
  output$plot_retraction_lag <- renderPlotly({
    d <- lag_diagnostics()$valid
    nih_mean <- mean(d$retraction_lag[d$Funding_Status == "NIH Funded"], na.rm = TRUE)
    oth_mean <- mean(d$retraction_lag[d$Funding_Status == "Not NIH Funded / Other"], na.rm = TRUE)
    ymax <- d %>% filter(retraction_lag <= LAG_AXIS_MAX) %>% count(retraction_lag) %>%
      summarise(m = max(n, na.rm = TRUE)) %>% pull(m)
    p <- d %>%
      rename(`Retraction Lag` = retraction_lag, `Funding Status` = Funding_Status) %>%
      count(`Retraction Lag`, `Funding Status`, name = "No. of articles") %>%
      ggplot(aes(x = `Retraction Lag`, y = `No. of articles`, fill = `Funding Status`)) +
      geom_col(width = 1, color = "white", position = "stack") +
      geom_vline(xintercept = nih_mean, color = "#005b96", linetype = "dashed", linewidth = 0.9) +
      geom_vline(xintercept = oth_mean, color = "gray40", linetype = "dashed", linewidth = 0.9) +
      annotate("text", x = LAG_AXIS_MAX * 0.45, y = ymax * 1.06, hjust = 0, vjust = 1,
               color = "#005b96", size = 3.5, fontface = "bold", label = sprintf("NIH mean = %.1f yr", nih_mean)) +
      annotate("text", x = LAG_AXIS_MAX * 0.45, y = ymax * 0.92, hjust = 0, vjust = 1,
               color = "gray40", size = 3.5, fontface = "bold", label = sprintf("non-NIH mean = %.1f yr", oth_mean)) +
      scale_fill_manual(values = corporate_colors) +
      coord_cartesian(xlim = c(0, LAG_AXIS_MAX)) +
      scale_y_continuous(expand = expansion(mult = c(0, 0.12))) +
      labs(x = "Years between Publication and Retraction", y = "No. of articles") +
      dashboard_theme
    ggplotly(p, tooltip = c("x", "y", "fill")) %>%
      layout(legend = list(orientation = "h", x = 0, y = 1.15, title = list(text = "")), margin = list(t = 50))
  })
  
  output$lag_note <- renderUI({
    diag <- lag_diagnostics()
    HTML(sprintf(
      paste0(
        "<p style='color: gray; font-size: 12px; margin-top: 10px;'>",
        "<em>Note: Distribution of the number of years elapsed between a paper's ",
        "publication date and its retraction date. Dashed vertical lines mark the mean lag for ",
        "NIH-funded (blue) and non-NIH (gray) papers. ",
        "The X axis is capped at %d years for readability; ",
        "<b>%s</b> paper(s) with a lag &gt; %d year(s) are excluded from the plot ",
        "but included in the means.</em></p>"
      ),
      LAG_AXIS_MAX, format(diag$outliers, big.mark = ","), LAG_AXIS_MAX
    ))
  })
  
  output$plot_publishers <- renderPlotly({
    publishers_data <- df_papers %>%
      drop_na(Publisher) %>%
      mutate(Publisher = str_trim(Publisher)) %>%
      filter(Publisher != "") %>%
      mutate(
        Publisher_Group = case_when(
          str_detect(Publisher, "(?i)Hindawi")                                         ~ "Hindawi (Wiley)",
          str_detect(Publisher, "(?i)Springer|Nature|BioMed Central|BMC|Palgrave")     ~ "Springer Nature",
          str_detect(Publisher, "(?i)Elsevier|Cell Press|Lancet|Pergamon")             ~ "Elsevier",
          str_detect(Publisher, "(?i)Wiley")                                           ~ "Wiley (excl. Hindawi)",
          str_detect(Publisher, "(?i)Taylor & Francis|Taylor and Francis|Routledge|Dove Medical") ~ "Taylor & Francis",
          str_detect(Publisher, "(?i)SAGE")                                            ~ "SAGE Publications",
          str_detect(Publisher, "(?i)IEEE")                                            ~ "IEEE",
          str_detect(Publisher, "(?i)MDPI")                                            ~ "MDPI",
          str_detect(Publisher, "(?i)Frontiers")                                       ~ "Frontiers",
          str_detect(Publisher, "(?i)Public Library of Science|PLOS|PLoS")             ~ "PLOS",
          str_detect(Publisher, "(?i)Oxford University Press|OUP")                     ~ "Oxford University Press",
          str_detect(Publisher, "(?i)Cambridge University Press|CUP")                  ~ "Cambridge University Press",
          TRUE                                                                         ~ Publisher
        )
      )
    
    top_20 <- publishers_data %>%
      count(Publisher_Group, sort = TRUE) %>%
      slice_head(n = 20) %>%
      pull(Publisher_Group)
    
    p <- publishers_data %>%
      filter(Publisher_Group %in% top_20) %>%
      mutate(Publisher_Group = factor(Publisher_Group, levels = rev(top_20))) %>%
      rename(`Publisher Group` = Publisher_Group, `Funding Status` = Funding_Status) %>%
      count(`Publisher Group`, `Funding Status`, name = "No. of articles") %>%
      ggplot(aes(y = `Publisher Group`, x = `No. of articles`, fill = `Funding Status`)) +
      geom_col(color = "white", position = "stack", width = 0.8) +
      scale_x_continuous(expand = expansion(mult = c(0, 0.05))) +
      scale_fill_manual(values = corporate_colors) +
      labs(y = "", x = "No. of articles") +
      dashboard_theme +
      theme(panel.grid.major.y = element_blank(), panel.grid.major.x = element_line(color = "gray90", linewidth = 0.5))
    
    n_categories <- length(top_20)
    
    ggplotly(p, tooltip = c("x", "y", "fill")) %>%
      layout(yaxis = list(range = c(0.5, n_categories + 0.5)),
             legend = list(orientation = "h", x = -0.5, y = 1.15, title = list(text = "")), 
             margin = list(t = 80, r = 20))
  })
  
  output$plot_domains <- renderPlotly({
    domains_data <- df_papers %>%
      drop_na(Subject) %>%
      mutate(Paper_ID = row_number()) %>%
      separate_rows(Subject, sep = ";") %>%
      mutate(Subject = str_trim(Subject)) %>%
      filter(Subject != "") %>%
      mutate(
        Acronym = str_extract(Subject, "^\\([^)]+\\)")
      ) %>%
      mutate(
        Domain_Full = case_when(
          Acronym == "(B/T)" ~ "Business & Technology",
          Acronym == "(BLS)" ~ "Biological Sciences",
          Acronym == "(ENV)" ~ "Environmental Sciences",
          Acronym == "(HSC)" ~ "Health Sciences",
          Acronym == "(HUM)" ~ "Humanities",
          Acronym == "(PHY)" ~ "Physical Sciences",
          Acronym == "(SOC)" ~ "Social Sciences",
          TRUE               ~ NA_character_
        )
      ) %>%
      filter(!is.na(Domain_Full)) %>%
      distinct(Paper_ID, Domain_Full, Funding_Status)
    
    domain_order <- domains_data %>% count(Domain_Full, sort = TRUE) %>% pull(Domain_Full)

    # Within-group denominators (all papers in each funding group), exactly as in Table 1 and the
    # Top Reasons panel: each % is the share of papers in that funding group classified in the domain.
    n_nih <- sum(df_papers$Funding_Status == "NIH Funded")
    n_oth <- sum(df_papers$Funding_Status == "Not NIH Funded / Other")

    # Non-NIH is the left part of each bar, NIH the right; place each % label at its segment centre
    # (computed explicitly so the label lands on the correct segment, not via position_stack).
    seg <- domains_data %>%
      mutate(Domain_Full = factor(Domain_Full, levels = rev(domain_order))) %>%
      rename(`Domain Full` = Domain_Full, `Funding Status` = Funding_Status) %>%
      count(`Domain Full`, `Funding Status`, name = "n_art") %>%
      mutate(`Funding Status` = factor(`Funding Status`, levels = c("NIH Funded", "Not NIH Funded / Other")),
             pct = n_art / ifelse(`Funding Status` == "NIH Funded", n_nih, n_oth) * 100) %>%
      group_by(`Domain Full`) %>%
      mutate(n_oth_cat = sum(n_art[`Funding Status` == "Not NIH Funded / Other"]),
             cat_total = sum(n_art),
             ypos = ifelse(`Funding Status` == "NIH Funded", n_oth_cat + n_art / 2, n_art / 2)) %>%
      ungroup() %>%
      # Hide the % label when its segment is too narrow to fit "XX.X%" (it would overflow the bar):
      # threshold at 13% of the widest stacked bar, calibrated so labels never spill past a segment.
      mutate(seg_label = ifelse(n_art >= 0.13 * max(cat_total), sprintf("%.1f%%", pct), ""))
    seg_nih <- seg %>% filter(`Funding Status` == "NIH Funded",             seg_label != "")
    seg_oth <- seg %>% filter(`Funding Status` == "Not NIH Funded / Other", seg_label != "")

    # Two fixed-colour text layers (inherit.aes = FALSE) so ggplotly keeps a clean two-entry legend;
    # labels sit at the explicit segment centres (ypos).
    p <- ggplot(seg, aes(x = `Domain Full`, y = n_art, fill = `Funding Status`)) +
      geom_col(color = "white", position = "stack") +
      geom_text(data = seg_oth, aes(x = `Domain Full`, y = ypos, label = seg_label), inherit.aes = FALSE,
                color = "gray20", fontface = "bold", size = 3.2) +
      geom_text(data = seg_nih, aes(x = `Domain Full`, y = ypos, label = seg_label), inherit.aes = FALSE,
                color = "white", fontface = "bold", size = 3.2) +
      coord_flip() +
      scale_fill_manual(values = corporate_colors) + scale_y_continuous(expand = expansion(mult = c(0, 0.05))) + labs(x = "", y = "No. of articles") + dashboard_theme +
      theme(panel.grid.major.y = element_blank(), panel.grid.major.x = element_line(color = "gray90", linewidth = 0.5))

    finalize_card_plot(p, left = 10)
  })
  
  output$plot_reasons <- renderPlotly({
    # Map each raw Retraction Watch label to its broad category (reason_clusters); labels not in
    # any category (incl. procedural/administrative meta-reasons) are dropped via inner_join.
    cat_data <- df_papers %>% mutate(Paper_ID = row_number()) %>%
      select(Paper_ID, Funding_Status, Reason) %>%
      drop_na(Reason) %>% separate_rows(Reason, sep = ";") %>% mutate(Reason = str_trim(Reason)) %>%
      inner_join(reason_cat_map, by = "Reason") %>%
      distinct(Paper_ID, Category, Funding_Status)

    # Within-group denominators (all papers in each funding group), exactly as in Table 1.
    n_nih <- sum(df_papers$Funding_Status == "NIH Funded")
    n_oth <- sum(df_papers$Funding_Status == "Not NIH Funded / Other")

    cat_order <- cat_data %>% count(Category, sort = TRUE) %>% pull(Category)
    wrap_cat <- function(x) str_wrap(x, width = 28)   # wrap long category names for the narrow card

    # Non-NIH is the left part of each bar, NIH the right; place each % label at its segment centre
    # (computed explicitly so the label lands on the correct segment, not via position_stack).
    seg <- cat_data %>%
      rename(`Funding Status` = Funding_Status) %>%
      count(Category, `Funding Status`, name = "n_art") %>%
      mutate(`Funding Status` = factor(`Funding Status`, levels = c("NIH Funded", "Not NIH Funded / Other")),
             pct = n_art / ifelse(`Funding Status` == "NIH Funded", n_nih, n_oth) * 100,
             Category = factor(wrap_cat(Category), levels = rev(wrap_cat(cat_order)))) %>%
      group_by(Category) %>%
      mutate(n_oth_cat = sum(n_art[`Funding Status` == "Not NIH Funded / Other"]),
             cat_total = sum(n_art),
             ypos = ifelse(`Funding Status` == "NIH Funded", n_oth_cat + n_art / 2, n_art / 2)) %>%
      ungroup() %>%
      # Hide the % label when its segment is too narrow to fit "XX.X%" (it would overflow the bar):
      # threshold at 13% of the widest stacked bar, calibrated so labels never spill past a segment.
      mutate(seg_label = ifelse(n_art >= 0.13 * max(cat_total), sprintf("%.1f%%", pct), ""))
    seg_nih <- seg %>% filter(`Funding Status` == "NIH Funded",             seg_label != "")
    seg_oth <- seg %>% filter(`Funding Status` == "Not NIH Funded / Other", seg_label != "")

    # Two fixed-colour text layers (NOT a colour aesthetic, inherit.aes = FALSE) so ggplotly keeps
    # a clean two-entry legend; labels sit at the explicit segment centres (ypos).
    p <- ggplot(seg, aes(x = Category, y = n_art, fill = `Funding Status`)) +
      geom_col(color = "white", position = "stack") +
      geom_text(data = seg_oth, aes(x = Category, y = ypos, label = seg_label), inherit.aes = FALSE,
                color = "gray20", fontface = "bold", size = 3.2) +
      geom_text(data = seg_nih, aes(x = Category, y = ypos, label = seg_label), inherit.aes = FALSE,
                color = "white", fontface = "bold", size = 3.2) +
      coord_flip() +
      scale_fill_manual(values = corporate_colors) +
      scale_y_continuous(expand = expansion(mult = c(0, 0.05))) + labs(x = "", y = "No. of articles") + dashboard_theme +
      theme(panel.grid.major.y = element_blank(), panel.grid.major.x = element_line(color = "gray90", linewidth = 0.5))

    finalize_card_plot(p, left = 10)
  })

  # --- Filtered Authors Reactive ---
  filtered_authors <- reactive({
    req(input$author_cohort_filter)
    if (input$author_cohort_filter == "one") {
      df_authors %>% filter(Num_Retractions == 1)
    } else if (input$author_cohort_filter == "more") {
      df_authors %>% filter(Num_Retractions > 1)
    } else {
      df_authors
    }
  })

  # --- Longitudinal impact ---
  df_timeline <- reactive({
    fa <- filtered_authors()
    total_cohort_authors <- n_distinct(fa$Original_Author_Name)

    # Per-author per-year funding (used to count how many authors have any grant per year)
    per_author_year <- fa %>%
      filter(diff_retracted >= -3 & diff_retracted <= 3) %>%
      group_by(Original_Author_Name, diff_retracted) %>%
      summarise(Annual_Funding = sum(Funding_Adjusted, na.rm = TRUE), .groups = "drop")

    fa %>% filter(diff_retracted >= -3 & diff_retracted <= 3) %>%
      group_by(diff_retracted) %>%
      summarise(Total_Adjusted_Funding = sum(Funding_Adjusted, na.rm = TRUE),
                Active_Grants = n_distinct(Grant_ID[!is.na(Grant_ID)]),
                .groups = "drop") %>%
      left_join(
        per_author_year %>%
          group_by(diff_retracted) %>%
          summarise(N_Funded = sum(Annual_Funding > 0), .groups = "drop"),
        by = "diff_retracted"
      ) %>%
      mutate(Cohort_Authors = total_cohort_authors,
             Average_Funding_Per_Author = Total_Adjusted_Funding / total_cohort_authors,
             Pct_With_Funding = N_Funded / total_cohort_authors * 100,
             Period_Label = ifelse(diff_retracted == 0, "Retraction Year (0)", "Normal Years"),
             # Funding index relative to year -3 (year -3 = 100)
             Funding_Index = Average_Funding_Per_Author /
                             Average_Funding_Per_Author[diff_retracted == -3] * 100)
  })

  timeline_colors <- c("Retraction Year (0)" = "#cccccc", "Normal Years" = "#005b96")

  # Within-author difference data (funding $ and active-grant count vs. year -3) for the
  # currently selected cohort, built like Figure 1 in policy_analysis.qmd.
  box_data <- reactive({
    fa <- filtered_authors()
    cohort_names <- unique(fa$Original_Author_Name)
    paf <- fa %>% filter(diff_retracted >= -3 & diff_retracted <= 3) %>%
      group_by(Original_Author_Name, diff_retracted) %>%
      summarise(Annual_Funding = sum(Funding_Adjusted, na.rm = TRUE), .groups = "drop")
    pag <- fa %>% filter(diff_retracted >= -3 & diff_retracted <= 3) %>%
      group_by(Original_Author_Name, diff_retracted) %>%
      summarise(N_Grants = n_distinct(Grant_ID[!is.na(Grant_ID)]), .groups = "drop")
    list(funding = make_diff_box_data(paf, cohort_names, "Annual_Funding"),
         grants  = make_diff_box_data(pag, cohort_names, "N_Grants"))
  })

  # Change in annual NIH funding vs. year -3 (Figure-1-style decomposed boxplot).
  output$plot_avg_funding <- renderPlotly({
    bd <- box_data()$funding
    st <- box_stats(bd); mn <- mean_line(bd)
    p <- make_box_panel_app(st, mn, whisker_cap(st, mn),
                            y_label = "Change in annual NIH funding", dollar_y = TRUE)
    ggplotly(p, tooltip = "text") %>%
      layout(legend = list(orientation = "h", x = 0, y = 1.12, title = list(text = "")),
             margin = list(b = 40, t = 30, l = 10, r = 10))
  })

  # Change in active NIH grants vs. year -3 (Figure-1-style decomposed boxplot).
  output$plot_active_grants <- renderPlotly({
    bd <- box_data()$grants
    st <- box_stats(bd); mn <- mean_line(bd)
    p <- make_box_panel_app(st, mn, whisker_cap(st, mn),
                            y_label = "Change in active NIH grants", dollar_y = FALSE)
    ggplotly(p, tooltip = "text") %>%
      layout(legend = list(orientation = "h", x = 0, y = 1.12, title = list(text = "")),
             margin = list(b = 40, t = 30, l = 10, r = 10))
  })
  
  output$plot_avg_funding_note <- renderUI({
    fa <- filtered_authors()
    total_authors <- n_distinct(fa$Original_Author_Name)
    HTML(paste0("<p style='color: gray; font-size: 12px; margin-top: 10px; font-style: italic;'>Note: For the cohort (", comma(total_authors), " authors), each box shows the distribution of the within-author change in annual NIH funding relative to the baseline year -3 (so year -3 is identically $0). Green boxes are the pre-retraction years (-3 to 0) and orange the post-retraction years (1 to 3); the box is the interquartile range, the centre line the median, the whiskers the 10th-90th percentiles, and the black line traces the mean change (the y-axis is fit to the whiskers). The per-author pre-vs-post medians and Wilcoxon signed-rank test reported in the statistics panel average each author's funding within the 3-year window and then take the median across the full cohort (authors with no funding contribute $0).</p>"))
  })
  
  # --- Statistical tests ---
  paired_data <- reactive({
    filtered_authors() %>% filter(diff_retracted >= -3 & diff_retracted <= 3 & diff_retracted != 0) %>%
      mutate(Period = ifelse(diff_retracted < 0, "Pre", "Post")) %>% group_by(Original_Author_Name, Period) %>%
      summarise(Annual_Funding = sum(Funding_Adjusted, na.rm = TRUE) / 3,
                Total_Grants = n_distinct(Grant_ID[!is.na(Grant_ID)]), .groups = "drop") %>%
      pivot_wider(names_from = Period, values_from = c(Annual_Funding, Total_Grants), values_fill = list(Annual_Funding = 0, Total_Grants = 0))
  })
  # --- ESTADÍSTICAS GLOBALES PARA LA FILA SUPERIOR ---
  output$stats_avg_funding <- renderUI({
    tl <- df_timeline()
    pd <- paired_data()

    # Cohort-wide paired data: add (0,0) rows for authors with no funding rows in the
    # +/-3 window, consistent with the cohort-wide imputation convention. Wilcoxon
    # signed-rank automatically ignores zero differences, so p-values are unchanged.
    cohort_set <- filtered_authors() %>% distinct(Original_Author_Name)
    pd_full <- cohort_set %>%
      left_join(pd, by = "Original_Author_Name") %>%
      mutate(across(c(Annual_Funding_Pre, Annual_Funding_Post, Total_Grants_Pre, Total_Grants_Post),
                    ~ ifelse(is.na(.x), 0, .x)))

    median_pre  <- median(pd_full$Annual_Funding_Pre)
    median_post <- median(pd_full$Annual_Funding_Post)
    pct_change <- if (median_pre > 0) (median_post - median_pre) / median_pre * 100 else NA_real_

    pct_funded_pre  <- mean(tl$Pct_With_Funding[tl$diff_retracted %in% c(-3, -2, -1)], na.rm = TRUE)
    pct_funded_post <- mean(tl$Pct_With_Funding[tl$diff_retracted %in% c(1, 2, 3)], na.rm = TRUE)
    pct_funded_change <- pct_funded_post - pct_funded_pre

    # Aggregate annual funding flowing to the cohort, averaged across each 3-year window
    total_funding_pre  <- mean(tl$Total_Adjusted_Funding[tl$diff_retracted %in% c(-3, -2, -1)], na.rm = TRUE)
    total_funding_post <- mean(tl$Total_Adjusted_Funding[tl$diff_retracted %in% c(1, 2, 3)], na.rm = TRUE)

    # Paired Wilcoxon signed-rank test on per-author funding
    test_funding <- wilcox.test(pd_full$Annual_Funding_Pre, pd_full$Annual_Funding_Post,
                                paired = TRUE, exact = FALSE)
    # McNemar test for the change in the proportion of authors holding any NIH funding
    test_funded <- mcnemar.test(table(
      factor(pd_full$Annual_Funding_Pre  > 0, levels = c(FALSE, TRUE)),
      factor(pd_full$Annual_Funding_Post > 0, levels = c(FALSE, TRUE))))

    pct_color <- ifelse(is.na(pct_change) || pct_change >= 0, "#5cb85c", "#d9534f")

    total_authors <- n_distinct(filtered_authors()$Original_Author_Name)
    active_authors_pre  <- sum(pd_full$Annual_Funding_Pre  > 0, na.rm = TRUE)
    active_authors_post <- sum(pd_full$Annual_Funding_Post > 0, na.rm = TRUE)
    # lost_all_pct is the share of PREVIOUSLY FUNDED authors (Pre > 0) who hold no NIH funding in
    # the 3 post-retraction years (denominator = n_funded_pre), exactly as in policy_analysis.qmd.
    # gained_pct stays over the whole cohort (also as in policy_analysis.qmd), hence the two boxes
    # below use different denominators (made explicit in their captions).
    n_funded_pre <- sum(pd_full$Annual_Funding_Pre > 0, na.rm = TRUE)
    lost_all_n <- sum(pd_full$Annual_Funding_Pre > 0 & pd_full$Annual_Funding_Post == 0, na.rm = TRUE)
    gained_n   <- sum(pd_full$Annual_Funding_Pre == 0 & pd_full$Annual_Funding_Post > 0, na.rm = TRUE)
    lost_all_pct <- (lost_all_n / n_funded_pre) * 100
    gained_pct   <- (gained_n   / total_authors) * 100

    pct_change_txt <- if (is.na(pct_change)) "n/a (median pre = $0)" else sprintf("%+.1f%%", pct_change)

    HTML(paste0(
      "<div style='padding: 10px;'>",
      "<h5 style='color: #005b96; font-weight: bold; margin-bottom: 20px; text-transform: uppercase;'>Per-Author Annual Funding (Median, 3-Year Windows)</h5>",
      "<div style='display: flex; justify-content: space-between; margin-bottom: 20px;'>",
      "<div style='text-align: center; width: 48%;'>",
      "<div style='font-size: 12px; color: #777; text-transform: uppercase; font-weight: bold;'>Median Pre-Retraction</div>",
      "<div style='font-size: 24px; font-weight: bold; color: #333;'>", dollar(median_pre, accuracy = 1), "</div>",
      "</div>",
      "<div style='text-align: center; width: 48%; border-left: 1px solid #eee;'>",
      "<div style='font-size: 12px; color: #777; text-transform: uppercase; font-weight: bold;'>Median Post-Retraction</div>",
      "<div style='font-size: 24px; font-weight: bold; color: #333;'>", dollar(median_post, accuracy = 1), "</div>",
      "</div>",
      "</div>",
      "<div style='text-align: center; margin-bottom: 20px;'>",
      "<span style='font-size: 14px; color: #666; text-transform: uppercase; font-weight: bold;'>Change: </span>",
      "<span style='font-size: 22px; font-weight: bold; color: ", pct_color, ";'>",
      pct_change_txt,
      "</span>",
      "<div style='font-size: 12px; color: #777; margin-top: 4px;'>Paired Wilcoxon signed-rank test: ", wilcox_txt(test_funding), "</div>",
      "<div style='font-size: 12px; color: #777; margin-top: 2px;'>Avg. annual % of cohort holding an active NIH grant: ",
      sprintf("%.1f%%", pct_funded_pre), " pre &rarr; ", sprintf("%.1f%%", pct_funded_post), " post (",
      sprintf("%+.1f pp", pct_funded_change), "; McNemar ", mcnemar_txt(test_funded), ")</div>",
      "</div>",

      # NUEVAS CAJAS DE TRANSICIÓN DE FONDOS
      "<div style='display: flex; justify-content: space-between; margin-bottom: 20px; font-size: 12px;'>",
      "<div style='width: 48%; background-color: #fdf2f2; padding: 10px; border-radius: 6px; border: 1px solid #fadcdc; text-align: center;'>",
      "<div style='color: #d9534f; font-weight: bold; margin-bottom: 5px;'>LOST ALL FUNDING</div>",
      "<div style='color: #777; margin-bottom: 5px;'>(Had Pre, $0 Post)</div>",
      "<div style='font-size: 18px; font-weight: bold; color: #333;'>", sprintf("%.1f%%", lost_all_pct), " <span style='font-size: 11px; font-weight: normal; color: #777;'>(", comma(lost_all_n), " of ", comma(n_funded_pre), " prev. funded)</span></div>",
      "</div>",
      "<div style='width: 48%; background-color: #f4fdf5; padding: 10px; border-radius: 6px; border: 1px solid #d4edda; text-align: center;'>",
      "<div style='color: #5cb85c; font-weight: bold; margin-bottom: 5px;'>GAINED FUNDING</div>",
      "<div style='color: #777; margin-bottom: 5px;'>($0 Pre, Had Post)</div>",
      "<div style='font-size: 18px; font-weight: bold; color: #333;'>", sprintf("%.1f%%", gained_pct), " <span style='font-size: 11px; font-weight: normal; color: #777;'>(", comma(gained_n), " of ", comma(total_authors), " in cohort)</span></div>",
      "</div>",
      "</div>",
      
      "<div style='background-color: #f8f9fa; padding: 15px; border-radius: 6px; border: 1px solid #e9ecef;'>",
      "<div style='font-size: 13px; color: #555; line-height: 1.4;'>We found that ", comma(active_authors_pre), " authors received at least some funding in the 3 years pre-retraction and ", comma(active_authors_post), " authors received at least some funding in the 3 years post-retraction.</div>",
      "</div>",
      "</div>"
    ))
  })
  
  output$stats_active_grants <- renderUI({
    fa <- filtered_authors()
    # Distinct active NIH grants in the 3-year pre/post windows (matches policy_analysis.qmd).
    grants_pre  <- fa %>% filter(diff_retracted %in% c(-3, -2, -1), !is.na(Grant_ID)) %>% pull(Grant_ID) %>% n_distinct()
    grants_post <- fa %>% filter(diff_retracted %in% c(1, 2, 3),  !is.na(Grant_ID)) %>% pull(Grant_ID) %>% n_distinct()
    pct_change  <- if (grants_pre > 0) (grants_post - grants_pre) / grants_pre * 100 else NA_real_
    pct_color   <- ifelse(is.na(pct_change) || pct_change < 0, "#d9534f", "#5cb85c")
    pct_change_txt <- if (is.na(pct_change)) "n/a" else sprintf("%+.1f%%", pct_change)

    # Paired Wilcoxon signed-rank on per-author grant counts (across the cohort)
    pd <- paired_data()
    cohort_set <- fa %>% distinct(Original_Author_Name)
    pd_full <- cohort_set %>%
      left_join(pd, by = "Original_Author_Name") %>%
      mutate(across(c(Annual_Funding_Pre, Annual_Funding_Post, Total_Grants_Pre, Total_Grants_Post),
                    ~ ifelse(is.na(.x), 0, .x)))
    test_grants <- wilcox.test(pd_full$Total_Grants_Pre, pd_full$Total_Grants_Post,
                               paired = TRUE, exact = FALSE)

    HTML(paste0(
      "<div style='padding: 10px;'>",
      "<h5 style='color: #005b96; font-weight: bold; margin-bottom: 20px; text-transform: uppercase;'>Distinct Active NIH Grants (3-Year Windows)</h5>",
      "<div style='display: flex; justify-content: space-between; margin-bottom: 20px;'>",
      "<div style='text-align: center; width: 48%;'>",
      "<div style='font-size: 12px; color: #777; text-transform: uppercase; font-weight: bold;'>Pre-Retraction</div>",
      "<div style='font-size: 24px; font-weight: bold; color: #333;'>", comma(grants_pre), "</div>",
      "</div>",
      "<div style='text-align: center; width: 48%; border-left: 1px solid #eee;'>",
      "<div style='font-size: 12px; color: #777; text-transform: uppercase; font-weight: bold;'>Post-Retraction</div>",
      "<div style='font-size: 24px; font-weight: bold; color: #333;'>", comma(grants_post), "</div>",
      "</div>",
      "</div>",
      "<div style='text-align: center; margin-bottom: 25px;'>",
      "<span style='font-size: 14px; color: #666; text-transform: uppercase; font-weight: bold;'>Change: </span>",
      "<span style='font-size: 22px; font-weight: bold; color: ", pct_color, ";'>",
      pct_change_txt,
      "</span>",
      "<div style='font-size: 12px; color: #777; margin-top: 4px;'>Paired Wilcoxon signed-rank on per-author grant counts: ", wilcox_txt(test_grants), "</div>",
      "</div>",
      "</div>"
    ))
  })

}

# 5. RUN APP
# ------------------------------------------------------------------------------
shinyApp(ui = ui, server = server)
