# =============================================================================
# STEP 6 - AUTHOR <-> NIH FUNDING MATCHER
# =============================================================================
# Joins retracted authors against the master PI ledger generated by step 3
# and computes, for each (author, grant) pair, the temporal offset between
# the grant's fiscal year and the author's first retraction year. The
# resulting table powers the longitudinal-impact charts in the Shiny app
# (e.g. "Funding before vs after first retraction").
#
# Matching is deliberately strict: authors are joined on the canonical
# "LAST_FIRST_MIDDLEINITIAL" key produced by :mod:`src.pi_history_generator`
# to minimise false positives (common-name collisions). Only the first
# and last author of each retracted paper are considered, which empirically
# captures the principal investigator role in most NIH-funded biomedical
# publications.
#
# Output (data/processed/Author_Funding_Matches.csv):
#     Original_Author_Name  str    First or last author from Retraction Watch
#     PI_NAME               str    PI name as it appears in the NIH ledger
#     Record_ID             str    Retraction Watch record identifier
#     Retraction_Year       int    Year of retraction (from RetractionDate)
#     Grant_ID              str    Full project number
#     Fiscal_Year           int    Fiscal year of the grant slice
#     Funding_Amount        float  Combined cost for that grant slice
#     diff_retracted        int    Fiscal_Year - first retraction year
# =============================================================================
import os
import re

import pandas as pd

from src.config import BASE_DIR

RWD_FILE = os.path.join(BASE_DIR, "data", "processed", "FINAL_Retractions_Costs_and_Pubs.csv")
PI_HISTORY_MASTER = os.path.join(BASE_DIR, "data", "processed", "MASTER_PI_History.csv")
OUTPUT_FILE = os.path.join(BASE_DIR, "data", "processed", "Author_Funding_Matches.csv")


def match_authors_to_funding():
    """Build the author <-> funding matches table.

    The function is split into clearly numbered phases so that progress is
    legible in CI logs:

    1. Load the Retraction Watch dataset.
    2. Project retracted papers onto their first and last authors.
    3. Compute the canonical match key per author.
    4. Filter the PI ledger to those keys and explode back to individual
       authors.
    5. Join with retraction dates and compute ``diff_retracted``.
    """
    print("1. Loading Retraction Watch data...")
    if not os.path.exists(RWD_FILE):
        print(f"[!] Error: {RWD_FILE} not found.")
        return

    df_rwd = pd.read_csv(RWD_FILE, low_memory=False)

    print("2. Linking authors to retraction dates...")
    author_col = 'Author' if 'Author' in df_rwd.columns else 'Authors'
    author_records = []

    for idx, row in df_rwd.iterrows():
        authors_str = str(row.get(author_col, ''))
        ret_date = row.get('RetractionDate', pd.NaT)
        record_id = row.get('Record ID', idx)

        authors = [a.strip() for a in authors_str.split(';') if a.strip()]
        if authors:
            # Keep first and last author only (typical PI/senior-author roles).
            for target in list(set([authors[0], authors[-1]])):
                author_records.append({
                    'Original_Author_Name': target,
                    'Record_ID': record_id,
                    'RetractionDate': ret_date,
                })

    df_author_papers = pd.DataFrame(author_records)
    df_author_papers['Retraction_Year'] = pd.to_datetime(
        df_author_papers['RetractionDate'], errors='coerce',
    ).dt.year
    df_author_papers = df_author_papers.dropna(subset=['Retraction_Year'])

    print("3. Building strict match keys (LAST_FIRST_MI)...")
    match_keys = {}
    for name in df_author_papers['Original_Author_Name'].unique():
        parts = name.upper().split()
        if len(parts) > 1:
            last = re.sub(r'[^A-Z]', '', parts[-1])
            first = re.sub(r'[^A-Z]', '', parts[0])
            mi = ""

            if len(parts) > 2:
                middle_word = re.sub(r'[^A-Z]', '', parts[1])
                if len(first) == 1 and len(middle_word) > 0:
                    # Pattern "A B Doe" -> first name is "AB".
                    first = f"{first}{middle_word}"
                elif len(middle_word) > 0:
                    # Otherwise keep only the middle initial.
                    mi = middle_word[0]

            key = f"{last}_{first}_{mi}".strip('_')

            if key not in match_keys:
                match_keys[key] = []
            match_keys[key].append(name)

    print("4. Joining against MASTER_PI_History...")
    if not os.path.exists(PI_HISTORY_MASTER):
        print(f"[!] Error: {PI_HISTORY_MASTER} not found. Run step 3 first.")
        return

    df_pi_history = pd.read_csv(PI_HISTORY_MASTER, low_memory=False)

    matched_nih = df_pi_history[df_pi_history['Match_Key'].isin(match_keys.keys())].copy()
    if matched_nih.empty:
        print("No matches found.")
        return

    matched_nih['Original_Author_Name'] = matched_nih['Match_Key'].map(match_keys)
    matched_nih = matched_nih.explode('Original_Author_Name')

    final_output = pd.merge(matched_nih, df_author_papers,
                            on='Original_Author_Name', how='inner')

    print("5. Computing diff_retracted (Fiscal_Year - first retraction year)...")
    final_output['diff_retracted'] = final_output['Fiscal_Year'] - final_output['Retraction_Year']

    cols = [
        'Original_Author_Name', 'PI_NAME', 'Record_ID', 'Retraction_Year',
        'Grant_ID', 'Fiscal_Year', 'Funding_Amount', 'diff_retracted',
    ]
    final_output = final_output[cols].sort_values(['Original_Author_Name', 'Fiscal_Year'])

    final_output.to_csv(OUTPUT_FILE, index=False)
    print(f"Author-funding matches written to: {OUTPUT_FILE}")


if __name__ == "__main__":
    match_authors_to_funding()
