# =============================================================================
# METADATA EXTRACTION FUNCTION
# =============================================================================
import pandas as pd # Pandas is used for data manipulation and tabular analysis.
from Bio import Entrez # Bio.Entrez provides a programmatic interface to query the NCBI E-utilities API.

def get_pubmed_metadata(doi, provided_pmid):
    """
    Queries the PubMed database to retrieve metadata for a specific publication.

    Parameters:
    - doi (str/float): The Digital Object Identifier of the target publication.
    - provided_pmid (str/float): The fallback PubMed ID provided by the dataset.

    Returns:
    - tuple: (Resolved PMID, String of concatenated Study Designs, List of Funding Dictionaries)
    """

    pmid_to_fetch = None

    # ---------------------------------------------------------
    # STEP 1A: Primary Query via DOI
    # ---------------------------------------------------------
    # Validate that the DOI is not a null value (NaN) and is a populated string.
    if pd.notna(doi) and str(doi).strip() != "":
        try:
            # Append the [DOI] search tag to restrict the query strictly to the DOI field.
            search_term = f"{doi}[DOI]"

            # Execute the search query. 'retmax=1' restricts the payload to the top result.
            handle = Entrez.esearch(db="pubmed", term=search_term, retmax=1)
            search_results = Entrez.read(handle)
            handle.close()

            # If the search yields a valid ID, assign it for the subsequent fetch request.
            if search_results['IdList']:
                pmid_to_fetch = search_results['IdList'][0]

        # Suppress exceptions during the search phase to allow the fallback mechanism to engage.
        except Exception:
            pass

    # ---------------------------------------------------------
    # STEP 1B: Fallback Query via Provided PMID
    # ---------------------------------------------------------
    # If the DOI query failed to return an ID, evaluate the provided baseline PMID.
    if not pmid_to_fetch and pd.notna(provided_pmid):

        # Sanitize the input: convert float representations (e.g., "123.0") to standard strings.
        clean_pmid = str(provided_pmid).split('.')[0].strip()

        # Validate that the sanitized string is a usable ID.
        if clean_pmid != "" and clean_pmid != "0":
            pmid_to_fetch = clean_pmid

    # If both primary and secondary resolution strategies fail, return null data markers.
    if not pmid_to_fetch:
        return "No valid DOI or PMID", "Unknown", []

    # ---------------------------------------------------------
    # STEP 2: Record Retrieval & XML Parsing (EFetch)
    # ---------------------------------------------------------
    try:
        # Retrieve the comprehensive publication record in XML format.
        handle = Entrez.efetch(db="pubmed", id=pmid_to_fetch, retmode="xml")
        fetch_records = Entrez.read(handle)
        handle.close()

        # Traverse the nested dictionary structure generated by Bio.Entrez.
        article = fetch_records['PubmedArticle'][0]['MedlineCitation']['Article']

        # --- Isolate Study Design Attributes ---
        study_designs = []
        # Conditional check to ensure the 'PublicationTypeList' key exists in the current record.
        if 'PublicationTypeList' in article:
            # Cast Biopython string objects to standard Python strings via list comprehension.
            study_designs = [str(pt) for pt in article['PublicationTypeList']]

        # --- Isolate Funding Support Attributes ---
        funding_data = []
        # Conditional check to ensure the 'GrantList' key exists.
        if 'GrantList' in article:
            for grant in article['GrantList']:
                # Utilize dictionary .get() method to safely assign default values if a key is absent.
                funding_data.append({
                    'Agency': grant.get('Agency', 'Unknown Agency'),
                    'GrantID': grant.get('GrantID', 'No ID')
                })

        # Return the resolved PMID, a semicolon-delimited string of study designs, and the funding list.
        return pmid_to_fetch, "; ".join(study_designs), funding_data

    # Log specific exception details if the XML parsing or network request fails.
    except Exception as e:
        return "Error", f"Error: {str(e)}", []